// ============================================================
// 🌍 ETHER MATERIALS — 740+ Matériaux Ultra-Complets
// Architecture · Intérieur · Terrain · Nature · Verre · Lumière
// Vêtements · Maisons · Emplois · Voitures · Effets Visuels
// ============================================================

import * as THREE from 'three'
import type { EtherMaterialDef } from '../types/index.js'

export const ETHER_MATERIALS: EtherMaterialDef[] = [

  // ============================================================
  // 🏗️ ARCHITECTURE — 60 matériaux
  // ============================================================
  { id: 'ew-concrete-main',      name: 'Béton Québec HD',          category: 'architecture', color: '#d9d6cd', roughness: 0.91, metalness: 0.00 },
  { id: 'ew-concrete-dark',      name: 'Béton Nuit',               category: 'architecture', color: '#242a31', roughness: 0.86, metalness: 0.05 },
  { id: 'ew-concrete-white',     name: 'Béton Blanc',              category: 'architecture', color: '#f0ede8', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-concrete-aged',      name: 'Béton Vieilli',            category: 'architecture', color: '#a8a29e', roughness: 0.95, metalness: 0.00 },
  { id: 'ew-concrete-raw',       name: 'Béton Brut',               category: 'architecture', color: '#b5b0a8', roughness: 0.93, metalness: 0.00 },
  { id: 'ew-concrete-polished',  name: 'Béton Poli',               category: 'architecture', color: '#ccc9c2', roughness: 0.40, metalness: 0.05 },
  { id: 'ew-stone-quebec',       name: 'Pierre Québec',            category: 'architecture', color: '#958f84', roughness: 0.96, metalness: 0.00 },
  { id: 'ew-stone-limestone',    name: 'Calcaire',                 category: 'architecture', color: '#d4c9b0', roughness: 0.94, metalness: 0.00 },
  { id: 'ew-stone-granite',      name: 'Granite',                  category: 'architecture', color: '#6b6461', roughness: 0.88, metalness: 0.02 },
  { id: 'ew-stone-marble-white', name: 'Marbre Blanc',             category: 'architecture', color: '#f5f2ee', roughness: 0.20, metalness: 0.05 },
  { id: 'ew-stone-marble-black', name: 'Marbre Noir',              category: 'architecture', color: '#1a1a1e', roughness: 0.18, metalness: 0.08 },
  { id: 'ew-stone-marble-green', name: 'Marbre Vert',              category: 'architecture', color: '#3d5c4a', roughness: 0.22, metalness: 0.04 },
  { id: 'ew-stone-sandstone',    name: 'Grès',                     category: 'architecture', color: '#c4a882', roughness: 0.97, metalness: 0.00 },
  { id: 'ew-stone-slate',        name: 'Ardoise',                  category: 'architecture', color: '#3d4147', roughness: 0.85, metalness: 0.05 },
  { id: 'ew-brick-red',          name: 'Brique Rouge',             category: 'architecture', color: '#8b3a2a', roughness: 0.93, metalness: 0.00 },
  { id: 'ew-brick-dark',         name: 'Brique Sombre',            category: 'architecture', color: '#3d2418', roughness: 0.94, metalness: 0.00 },
  { id: 'ew-brick-white',        name: 'Brique Blanche',           category: 'architecture', color: '#e8e4dc', roughness: 0.92, metalness: 0.00 },
  { id: 'ew-brick-old',          name: 'Brique Ancienne',          category: 'architecture', color: '#7a4030', roughness: 0.96, metalness: 0.00 },
  { id: 'ew-metal-black',        name: 'Métal Noir Architectural',  category: 'architecture', color: '#0b1118', roughness: 0.30, metalness: 0.82 },
  { id: 'ew-metal-zinc',         name: 'Zinc Architectural',       category: 'architecture', color: '#8a9099', roughness: 0.55, metalness: 0.75 },
  { id: 'ew-metal-copper-new',   name: 'Cuivre Neuf',              category: 'architecture', color: '#b87333', roughness: 0.35, metalness: 0.88 },
  { id: 'ew-metal-copper-aged',  name: 'Cuivre Patiné',            category: 'architecture', color: '#4a8c6e', roughness: 0.70, metalness: 0.60 },
  { id: 'ew-metal-corten',       name: 'Acier Corten',             category: 'architecture', color: '#7a3b1e', roughness: 0.80, metalness: 0.65 },
  { id: 'ew-metal-galvanized',   name: 'Acier Galvanisé',          category: 'architecture', color: '#c0c8d0', roughness: 0.45, metalness: 0.80 },
  { id: 'ew-stucco-white',       name: 'Stuc Blanc',               category: 'architecture', color: '#f2efe8', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-stucco-beige',       name: 'Stuc Beige',               category: 'architecture', color: '#d4c8a8', roughness: 0.87, metalness: 0.00 },
  { id: 'ew-stucco-grey',        name: 'Stuc Gris',                category: 'architecture', color: '#b0aca8', roughness: 0.89, metalness: 0.00 },
  { id: 'ew-cladding-wood',      name: 'Bardage Bois',             category: 'architecture', color: '#7a5c3c', roughness: 0.82, metalness: 0.00 },
  { id: 'ew-cladding-fiber',     name: 'Bardage Fibre-Ciment',     category: 'architecture', color: '#c8c4bc', roughness: 0.85, metalness: 0.00 },
  { id: 'ew-cladding-vinyl',     name: 'Revêtement Vinyle Blanc',  category: 'architecture', color: '#f0ece4', roughness: 0.75, metalness: 0.00 },
  { id: 'ew-cladding-metal',     name: 'Bardage Métal Gris',       category: 'architecture', color: '#7a8088', roughness: 0.50, metalness: 0.70 },
  { id: 'ew-roof-asphalt',       name: 'Toiture Asphalte Noire',   category: 'architecture', color: '#1c1c20', roughness: 0.97, metalness: 0.00 },
  { id: 'ew-roof-clay',          name: 'Toiture Tuile Terre',      category: 'architecture', color: '#8c4a2a', roughness: 0.90, metalness: 0.00 },
  { id: 'ew-roof-metal',         name: 'Toiture Métal',            category: 'architecture', color: '#6a7078', roughness: 0.55, metalness: 0.72 },
  { id: 'ew-roof-green',         name: 'Toiture Verte',            category: 'architecture', color: '#3a5c30', roughness: 0.98, metalness: 0.00 },
  { id: 'ew-foundation-concrete',name: 'Fondation Béton Brut',     category: 'architecture', color: '#9a9590', roughness: 0.95, metalness: 0.00 },
  { id: 'ew-paint-white',        name: 'Peinture Blanche Mat',     category: 'architecture', color: '#f8f6f2', roughness: 0.92, metalness: 0.00 },
  { id: 'ew-paint-grey-dark',    name: 'Peinture Gris Anthracite', category: 'architecture', color: '#2c3038', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-paint-black',        name: 'Peinture Noire',           category: 'architecture', color: '#0e0e10', roughness: 0.90, metalness: 0.00 },
  { id: 'ew-paint-beige',        name: 'Peinture Beige Chaud',     category: 'architecture', color: '#d4c8a8', roughness: 0.91, metalness: 0.00 },
  { id: 'ew-paint-blue-slate',   name: 'Peinture Bleu Ardoise',    category: 'architecture', color: '#4a5c72', roughness: 0.89, metalness: 0.00 },
  { id: 'ew-paint-green-sage',   name: 'Peinture Vert Sauge',      category: 'architecture', color: '#6a8068', roughness: 0.90, metalness: 0.00 },
  { id: 'ew-paint-red-barn',     name: 'Peinture Rouge Grange',    category: 'architecture', color: '#7a2c1e', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-precast-panel',      name: 'Panneau Préfabriqué',      category: 'architecture', color: '#c8c4be', roughness: 0.87, metalness: 0.00 },
  { id: 'ew-insulation-panel',   name: 'Panneau Isolant',          category: 'architecture', color: '#e8e4d8', roughness: 0.90, metalness: 0.00 },
  { id: 'ew-curtain-wall-frame', name: 'Mur Rideau Cadre Alu',     category: 'architecture', color: '#9aa0a8', roughness: 0.40, metalness: 0.80 },
  { id: 'ew-handrail-steel',     name: 'Main Courante Acier',      category: 'architecture', color: '#8a9099', roughness: 0.35, metalness: 0.90 },
  { id: 'ew-column-concrete',    name: 'Colonne Béton',            category: 'architecture', color: '#c0bcb4', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-column-steel',       name: 'Colonne Acier HEA',        category: 'architecture', color: '#5a6068', roughness: 0.40, metalness: 0.85 },
  { id: 'ew-column-marble',      name: 'Colonne Marbre Classique', category: 'architecture', color: '#e8e4dc', roughness: 0.22, metalness: 0.04 },
  { id: 'ew-sidewalk-concrete',  name: 'Trottoir Béton',           category: 'architecture', color: '#c8c4bc', roughness: 0.93, metalness: 0.00 },
  { id: 'ew-sidewalk-paving',    name: 'Pavage Gris',              category: 'architecture', color: '#9a9690', roughness: 0.90, metalness: 0.00 },
  { id: 'ew-curb-concrete',      name: 'Bordure Béton',            category: 'architecture', color: '#b8b4ae', roughness: 0.91, metalness: 0.00 },
  { id: 'ew-fence-wood',         name: 'Clôture Bois',             category: 'architecture', color: '#8a6848', roughness: 0.85, metalness: 0.00 },
  { id: 'ew-fence-chain',        name: 'Clôture Chaîne',           category: 'architecture', color: '#7a8088', roughness: 0.55, metalness: 0.70 },
  { id: 'ew-fence-vinyl',        name: 'Clôture Vinyle Blanc',     category: 'architecture', color: '#f0ede6', roughness: 0.75, metalness: 0.00 },
  { id: 'ew-gutter-aluminum',    name: 'Gouttière Aluminium',      category: 'architecture', color: '#b0b8c0', roughness: 0.45, metalness: 0.75 },
  { id: 'ew-chimney-brick',      name: 'Cheminée Brique',          category: 'architecture', color: '#7a3c28', roughness: 0.93, metalness: 0.00 },
  { id: 'ew-deck-composite',     name: 'Terrasse Composite',       category: 'architecture', color: '#6a5040', roughness: 0.72, metalness: 0.00 },
  { id: 'ew-retaining-wall',     name: 'Mur de Soutènement',       category: 'architecture', color: '#8a8480', roughness: 0.94, metalness: 0.00 },
  { id: 'ew-fire-escape-metal',  name: 'Escalier Secours Métal',   category: 'architecture', color: '#4a5058', roughness: 0.55, metalness: 0.75 },

  // ============================================================
  // 🏠 MAISONS — 80 matériaux
  // ============================================================
  { id: 'ew-house-wood-pine',    name: 'Pin Naturel Maison',       category: 'house', color: '#c8a070', roughness: 0.75, metalness: 0.00 },
  { id: 'ew-house-wood-cedar',   name: 'Cèdre Rouge',              category: 'house', color: '#8b4c30', roughness: 0.78, metalness: 0.00 },
  { id: 'ew-house-wood-oak',     name: 'Chêne Maison',             category: 'house', color: '#a07840', roughness: 0.65, metalness: 0.00 },
  { id: 'ew-house-wood-maple',   name: 'Érable Québec',            category: 'house', color: '#d4a870', roughness: 0.60, metalness: 0.00 },
  { id: 'ew-house-wood-walnut',  name: 'Noyer Luxe',               category: 'house', color: '#4a2c18', roughness: 0.55, metalness: 0.00 },
  { id: 'ew-house-wood-birch',   name: 'Bouleau Blanc',            category: 'house', color: '#e8dcc8', roughness: 0.62, metalness: 0.00 },
  { id: 'ew-house-wood-teak',    name: 'Teck Extérieur',           category: 'house', color: '#7a5530', roughness: 0.50, metalness: 0.00 },
  { id: 'ew-house-wood-aged',    name: 'Bois Grisé Intempéries',   category: 'house', color: '#8a8880', roughness: 0.92, metalness: 0.00 },
  { id: 'ew-house-siding-white', name: 'Revêtement Blanc',         category: 'house', color: '#f2efea', roughness: 0.80, metalness: 0.00 },
  { id: 'ew-house-siding-blue',  name: 'Revêtement Bleu',          category: 'house', color: '#3a5c7a', roughness: 0.80, metalness: 0.00 },
  { id: 'ew-house-siding-green', name: 'Revêtement Vert',          category: 'house', color: '#3a5c38', roughness: 0.80, metalness: 0.00 },
  { id: 'ew-house-siding-grey',  name: 'Revêtement Gris',          category: 'house', color: '#7a8088', roughness: 0.80, metalness: 0.00 },
  { id: 'ew-house-door-wood',    name: 'Porte Bois Massif',        category: 'house', color: '#5a3820', roughness: 0.65, metalness: 0.00 },
  { id: 'ew-house-door-steel',   name: 'Porte Acier Isolée',       category: 'house', color: '#3c4048', roughness: 0.55, metalness: 0.70 },
  { id: 'ew-house-door-fiberg',  name: 'Porte Fibre de Verre',     category: 'house', color: '#a89880', roughness: 0.60, metalness: 0.00 },
  { id: 'ew-house-window-frame', name: 'Cadre Fenêtre PVC Blanc',  category: 'house', color: '#f0ede8', roughness: 0.75, metalness: 0.00 },
  { id: 'ew-house-window-wood',  name: 'Cadre Fenêtre Bois',       category: 'house', color: '#8a6040', roughness: 0.70, metalness: 0.00 },
  { id: 'ew-house-window-alu',   name: 'Cadre Fenêtre Aluminium',  category: 'house', color: '#9aa0a8', roughness: 0.40, metalness: 0.78 },
  { id: 'ew-house-floor-tile',   name: 'Plancher Céramique',       category: 'house', color: '#d8d4cc', roughness: 0.35, metalness: 0.00 },
  { id: 'ew-house-floor-vinyl',  name: 'Plancher Vinyle',          category: 'house', color: '#c0b898', roughness: 0.55, metalness: 0.00 },
  { id: 'ew-house-floor-carpet', name: 'Tapis Gris Chambre',       category: 'house', color: '#9090a0', roughness: 0.95, metalness: 0.00 },
  { id: 'ew-house-floor-carpet-beige', name: 'Tapis Beige',        category: 'house', color: '#c8b898', roughness: 0.94, metalness: 0.00 },
  { id: 'ew-house-floor-stone',  name: 'Plancher Pierre Nat.',     category: 'house', color: '#a8a098', roughness: 0.80, metalness: 0.00 },
  { id: 'ew-house-wall-drywall', name: 'Gypse Blanc Standard',     category: 'house', color: '#f4f1ec', roughness: 0.92, metalness: 0.00 },
  { id: 'ew-house-wall-plaster', name: 'Plâtre Ancien',            category: 'house', color: '#e8e0d0', roughness: 0.90, metalness: 0.00 },
  { id: 'ew-house-wall-brick',   name: 'Mur Brique Intérieur',     category: 'house', color: '#8a4030', roughness: 0.92, metalness: 0.00 },
  { id: 'ew-house-wall-panel',   name: 'Lambris Bois',             category: 'house', color: '#a87848', roughness: 0.68, metalness: 0.00 },
  { id: 'ew-house-ceiling-white',name: 'Plafond Blanc',            category: 'house', color: '#fafaf8', roughness: 0.93, metalness: 0.00 },
  { id: 'ew-house-ceiling-wood', name: 'Plafond Bois',             category: 'house', color: '#b08050', roughness: 0.70, metalness: 0.00 },
  { id: 'ew-house-ceiling-coffered', name: 'Plafond Caissons',     category: 'house', color: '#d8d0c0', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-house-stair-wood',   name: 'Escalier Bois Naturel',    category: 'house', color: '#9a7050', roughness: 0.60, metalness: 0.00 },
  { id: 'ew-house-stair-steel',  name: 'Escalier Acier',           category: 'house', color: '#7a8088', roughness: 0.42, metalness: 0.80 },
  { id: 'ew-house-stair-marble', name: 'Escalier Marbre',          category: 'house', color: '#e8e4dc', roughness: 0.22, metalness: 0.04 },
  { id: 'ew-house-railing-wood', name: 'Rampe Bois',               category: 'house', color: '#8a6040', roughness: 0.60, metalness: 0.00 },
  { id: 'ew-house-railing-iron', name: 'Rampe Fer Forgé',          category: 'house', color: '#2a2830', roughness: 0.50, metalness: 0.75 },
  { id: 'ew-house-garage-door',  name: 'Porte Garage',             category: 'house', color: '#d0ccc4', roughness: 0.70, metalness: 0.30 },
  { id: 'ew-house-garage-metal', name: 'Porte Garage Métal',       category: 'house', color: '#8a9099', roughness: 0.55, metalness: 0.65 },
  { id: 'ew-house-basement',     name: 'Sous-Sol Béton Nu',        category: 'house', color: '#9a9590', roughness: 0.95, metalness: 0.00 },
  { id: 'ew-house-porch-wood',   name: 'Galerie Bois',             category: 'house', color: '#a88060', roughness: 0.75, metalness: 0.00 },
  { id: 'ew-house-porch-tile',   name: 'Galerie Céramique',        category: 'house', color: '#c8c0b4', roughness: 0.45, metalness: 0.00 },
  { id: 'ew-house-kitchen-tile', name: 'Dosseret Cuisine Blanc',   category: 'house', color: '#f4f2ee', roughness: 0.30, metalness: 0.00 },
  { id: 'ew-house-kitchen-metro',name: 'Métro Blanc Brillant',     category: 'house', color: '#f6f4f0', roughness: 0.15, metalness: 0.05 },
  { id: 'ew-house-bath-tile',    name: 'Carreau Salle de Bain',    category: 'house', color: '#e8e6e2', roughness: 0.30, metalness: 0.00 },
  { id: 'ew-house-bath-marble',  name: 'Marbre Salle de Bain',     category: 'house', color: '#f0ece8', roughness: 0.20, metalness: 0.05 },
  { id: 'ew-house-insulation',   name: 'Isolant Laine Minérale',   category: 'house', color: '#f0d890', roughness: 0.98, metalness: 0.00 },
  { id: 'ew-house-vapor-barrier',name: 'Pare-Vapeur Poly',         category: 'house', color: '#9ad0e8', roughness: 0.60, metalness: 0.05, transparent: true, opacity: 0.70 },
  { id: 'ew-house-subfloor',     name: 'Sous-Plancher OSB',        category: 'house', color: '#c8a870', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-house-sheathing',    name: 'Panneau Contreplaqué',     category: 'house', color: '#c0a060', roughness: 0.85, metalness: 0.00 },
  { id: 'ew-house-pool-liner',   name: 'Liner Piscine Bleu',       category: 'house', color: '#1a7ab8', roughness: 0.40, metalness: 0.05, transparent: true, opacity: 0.80 },
  { id: 'ew-house-pool-tile',    name: 'Carrelage Piscine',        category: 'house', color: '#5aacd4', roughness: 0.25, metalness: 0.05 },
  { id: 'ew-house-shed-metal',   name: 'Cabanon Métal',            category: 'house', color: '#7a9098', roughness: 0.60, metalness: 0.65 },
  { id: 'ew-house-greenhouse',   name: 'Serre Verre',              category: 'house', color: '#c0e8f0', roughness: 0.08, metalness: 0.10, transparent: true, opacity: 0.60 },
  { id: 'ew-house-skylight',     name: 'Puits de Lumière',         category: 'house', color: '#d0e8f8', roughness: 0.06, metalness: 0.12, transparent: true, opacity: 0.50 },
  { id: 'ew-house-fireplace',    name: 'Foyer Pierre Nat.',        category: 'house', color: '#6a5a50', roughness: 0.90, metalness: 0.00 },
  { id: 'ew-house-fireplace-tile',name: 'Foyer Carrelage Noir',    category: 'house', color: '#1a1c20', roughness: 0.35, metalness: 0.05 },
  { id: 'ew-house-trim-white',   name: 'Moulure Blanche',          category: 'house', color: '#f6f4f0', roughness: 0.80, metalness: 0.00 },
  { id: 'ew-house-trim-wood',    name: 'Moulure Bois',             category: 'house', color: '#b89060', roughness: 0.60, metalness: 0.00 },
  { id: 'ew-house-baseboard',    name: 'Plinthe Blanche',          category: 'house', color: '#f4f1ec', roughness: 0.82, metalness: 0.00 },
  { id: 'ew-house-column-porch', name: 'Colonne Galerie Bois',     category: 'house', color: '#f0ede8', roughness: 0.78, metalness: 0.00 },
  { id: 'ew-house-pergola',      name: 'Pergola Bois',             category: 'house', color: '#b09070', roughness: 0.80, metalness: 0.00 },
  { id: 'ew-house-fence-picket', name: 'Clôture Piquet Blanc',     category: 'house', color: '#f2f0ec', roughness: 0.82, metalness: 0.00 },
  { id: 'ew-house-driveway',     name: 'Entrée Asphalte',          category: 'house', color: '#2a2c30', roughness: 0.96, metalness: 0.00 },
  { id: 'ew-house-driveway-pave',name: 'Entrée Pavé Uni',          category: 'house', color: '#9a9490', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-house-mailbox',      name: 'Boîte aux Lettres',        category: 'house', color: '#4a5058', roughness: 0.55, metalness: 0.72 },
  { id: 'ew-house-ac-unit',      name: 'Unité Climatisation',      category: 'house', color: '#c8ccd0', roughness: 0.60, metalness: 0.55 },
  { id: 'ew-house-solar-panel',  name: 'Panneau Solaire',          category: 'house', color: '#1a2030', roughness: 0.30, metalness: 0.40, emissive: '#002040', emissiveIntensity: 0.05 },
  { id: 'ew-house-water-heater', name: 'Chauffe-Eau',              category: 'house', color: '#e0dcd4', roughness: 0.55, metalness: 0.50 },
  { id: 'ew-house-furnace',      name: 'Fournaise',                category: 'house', color: '#9a9898', roughness: 0.60, metalness: 0.60 },
  { id: 'ew-house-ductwork',     name: 'Conduit HVAC',             category: 'house', color: '#c0c4c8', roughness: 0.50, metalness: 0.65 },
  { id: 'ew-house-pipe-copper',  name: 'Tuyauterie Cuivre',        category: 'house', color: '#b87333', roughness: 0.40, metalness: 0.85 },
  { id: 'ew-house-electrical',   name: 'Panneau Électrique',       category: 'house', color: '#3a3c40', roughness: 0.65, metalness: 0.50 },
  { id: 'ew-house-breaker-box',  name: 'Boîtier Disjoncteur',      category: 'house', color: '#e8e4dc', roughness: 0.70, metalness: 0.30 },
  { id: 'ew-house-attic-hatch',  name: 'Trappe Grenier',           category: 'house', color: '#d8d4cc', roughness: 0.80, metalness: 0.00 },
  { id: 'ew-house-exterior-light',name: 'Luminaire Extérieur',     category: 'house', color: '#3a3830', roughness: 0.50, metalness: 0.75, emissive: '#ffd39a', emissiveIntensity: 0.80 },
  { id: 'ew-house-doorbell',     name: 'Sonnette',                 category: 'house', color: '#f0ede8', roughness: 0.60, metalness: 0.40, emissive: '#ffffff', emissiveIntensity: 0.15 },
  { id: 'ew-house-intercom',     name: 'Interphone',               category: 'house', color: '#2a2c30', roughness: 0.45, metalness: 0.65 },
  { id: 'ew-house-smart-lock',   name: 'Serrure Intelligente',     category: 'house', color: '#1a1c20', roughness: 0.40, metalness: 0.80, emissive: '#00e8ff', emissiveIntensity: 0.20 },

  // ============================================================
  // 🪑 INTÉRIEUR — 70 matériaux
  // ============================================================
  { id: 'ew-int-wall-warm',      name: 'Mur Intérieur Chaud',      category: 'interior', color: '#f3f0e8', roughness: 0.82, metalness: 0.00 },
  { id: 'ew-int-wall-cool',      name: 'Mur Gris Frais',           category: 'interior', color: '#d8dce0', roughness: 0.84, metalness: 0.00 },
  { id: 'ew-int-wall-sage',      name: 'Mur Vert Sauge',           category: 'interior', color: '#c0c8b8', roughness: 0.83, metalness: 0.00 },
  { id: 'ew-int-wall-navy',      name: 'Mur Bleu Marine',          category: 'interior', color: '#2a3850', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-int-wall-charcoal',  name: 'Mur Charbon',              category: 'interior', color: '#2c3038', roughness: 0.87, metalness: 0.00 },
  { id: 'ew-int-floor-hardwood', name: 'Parquet Chêne',            category: 'interior', color: '#a87546', roughness: 0.38, metalness: 0.00 },
  { id: 'ew-int-floor-dark',     name: 'Parquet Wengé',            category: 'interior', color: '#2a1c10', roughness: 0.40, metalness: 0.00 },
  { id: 'ew-int-floor-light',    name: 'Parquet Frêne Clair',      category: 'interior', color: '#dcc8a0', roughness: 0.45, metalness: 0.00 },
  { id: 'ew-int-floor-herring',  name: 'Parquet Chevron',          category: 'interior', color: '#b08850', roughness: 0.42, metalness: 0.00 },
  { id: 'ew-int-floor-concrete', name: 'Sol Béton Ciré',           category: 'interior', color: '#c0bdb6', roughness: 0.35, metalness: 0.05 },
  { id: 'ew-int-floor-epoxy',    name: 'Époxy Gris Brillant',      category: 'interior', color: '#9aa0a8', roughness: 0.15, metalness: 0.10 },
  { id: 'ew-int-floor-terrazzo', name: 'Terrazzo',                 category: 'interior', color: '#d4c8bc', roughness: 0.25, metalness: 0.03 },
  { id: 'ew-int-sofa-grey',      name: 'Sofa Tissu Graphite',      category: 'interior', color: '#303843', roughness: 0.87, metalness: 0.00 },
  { id: 'ew-int-sofa-beige',     name: 'Sofa Lin Beige',           category: 'interior', color: '#c8b898', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-int-sofa-navy',      name: 'Sofa Velours Marine',      category: 'interior', color: '#1e2d48', roughness: 0.80, metalness: 0.00 },
  { id: 'ew-int-sofa-leather-blk',name: 'Canapé Cuir Noir',        category: 'interior', color: '#121214', roughness: 0.40, metalness: 0.05 },
  { id: 'ew-int-sofa-leather-br', name: 'Canapé Cuir Brun',        category: 'interior', color: '#6a4028', roughness: 0.42, metalness: 0.03 },
  { id: 'ew-int-chair-fabric',   name: 'Chaise Tissu',             category: 'interior', color: '#8090a0', roughness: 0.85, metalness: 0.00 },
  { id: 'ew-int-chair-velvet',   name: 'Chaise Velours Vert',      category: 'interior', color: '#2a5040', roughness: 0.78, metalness: 0.00 },
  { id: 'ew-int-table-wood',     name: 'Table Bois Massif',        category: 'interior', color: '#7a5830', roughness: 0.50, metalness: 0.00 },
  { id: 'ew-int-table-marble',   name: 'Table Marbre',             category: 'interior', color: '#f0ece8', roughness: 0.18, metalness: 0.05 },
  { id: 'ew-int-table-glass',    name: 'Table Verre',              category: 'interior', color: '#c0d8e8', roughness: 0.05, metalness: 0.10, transparent: true, opacity: 0.70 },
  { id: 'ew-int-table-steel',    name: 'Table Acier Brossé',       category: 'interior', color: '#9aa0a8', roughness: 0.38, metalness: 0.90 },
  { id: 'ew-int-counter-quartz', name: 'Comptoir Quartz Blanc',    category: 'interior', color: '#f0ede8', roughness: 0.22, metalness: 0.02 },
  { id: 'ew-int-counter-granite',name: 'Comptoir Granite Noir',    category: 'interior', color: '#1c1c20', roughness: 0.25, metalness: 0.05 },
  { id: 'ew-int-counter-wood',   name: 'Comptoir Bois Boucher',    category: 'interior', color: '#a87848', roughness: 0.52, metalness: 0.00 },
  { id: 'ew-int-cabinet-white',  name: 'Armoire Blanc Laqué',      category: 'interior', color: '#f6f4f2', roughness: 0.30, metalness: 0.05 },
  { id: 'ew-int-cabinet-wood',   name: 'Armoire Bois Naturel',     category: 'interior', color: '#b08855', roughness: 0.55, metalness: 0.00 },
  { id: 'ew-int-cabinet-grey',   name: 'Armoire Gris Anthracite',  category: 'interior', color: '#3c4048', roughness: 0.32, metalness: 0.05 },
  { id: 'ew-int-rug-grey',       name: 'Tapis Gris Nuit',          category: 'interior', color: '#171c24', roughness: 0.90, metalness: 0.00 },
  { id: 'ew-int-rug-beige',      name: 'Tapis Beige Jute',         category: 'interior', color: '#c8b890', roughness: 0.93, metalness: 0.00 },
  { id: 'ew-int-rug-pattern',    name: 'Tapis Motif',              category: 'interior', color: '#8a6858', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-int-curtain-white',  name: 'Rideau Blanc Lin',         category: 'interior', color: '#f8f6f2', roughness: 0.90, metalness: 0.00, transparent: true, opacity: 0.85 },
  { id: 'ew-int-curtain-grey',   name: 'Rideau Gris Lourd',        category: 'interior', color: '#5a6068', roughness: 0.88, metalness: 0.00, transparent: true, opacity: 0.92 },
  { id: 'ew-int-curtain-navy',   name: 'Rideau Velours Marine',    category: 'interior', color: '#1a2440', roughness: 0.82, metalness: 0.00 },
  { id: 'ew-int-pillow-linen',   name: 'Coussin Lin',              category: 'interior', color: '#d8c8a8', roughness: 0.92, metalness: 0.00 },
  { id: 'ew-int-pillow-velvet',  name: 'Coussin Velours',          category: 'interior', color: '#3a4858', roughness: 0.80, metalness: 0.00 },
  { id: 'ew-int-ceramic-white',  name: 'Céramique Blanche',        category: 'interior', color: '#f6f7f3', roughness: 0.40, metalness: 0.00 },
  { id: 'ew-int-ceramic-black',  name: 'Céramique Noire Mat',      category: 'interior', color: '#1a1c1e', roughness: 0.38, metalness: 0.02 },
  { id: 'ew-int-ceramic-metro',  name: 'Métro Blanc Salle de Bain',category: 'interior', color: '#f4f2ee', roughness: 0.18, metalness: 0.03 },
  { id: 'ew-int-appliance-steel',name: 'Électroménager Acier',     category: 'interior', color: '#b0b8c0', roughness: 0.30, metalness: 0.88 },
  { id: 'ew-int-appliance-black',name: 'Électroménager Noir',      category: 'interior', color: '#1a1c20', roughness: 0.40, metalness: 0.60 },
  { id: 'ew-int-sink-steel',     name: 'Évier Inox',               category: 'interior', color: '#b0b8c0', roughness: 0.28, metalness: 0.92 },
  { id: 'ew-int-sink-white',     name: 'Évier Porcelaine',         category: 'interior', color: '#f8f6f4', roughness: 0.22, metalness: 0.03 },
  { id: 'ew-int-tub-white',      name: 'Bain Porcelaine',          category: 'interior', color: '#f6f4f2', roughness: 0.20, metalness: 0.04 },
  { id: 'ew-int-shower-glass',   name: 'Porte Douche',             category: 'interior', color: '#c8dce8', roughness: 0.04, metalness: 0.12, transparent: true, opacity: 0.55 },
  { id: 'ew-int-toilet-white',   name: 'Toilette Porcelaine',      category: 'interior', color: '#f8f7f4', roughness: 0.25, metalness: 0.03 },
  { id: 'ew-int-mirror',         name: 'Miroir',                   category: 'interior', color: '#c0d0e0', roughness: 0.02, metalness: 0.95, transparent: true, opacity: 0.90 },
  { id: 'ew-int-bookshelf-wood', name: 'Bibliothèque Bois',        category: 'interior', color: '#9a7040', roughness: 0.58, metalness: 0.00 },
  { id: 'ew-int-bed-frame-wood', name: 'Lit Bois Massif',          category: 'interior', color: '#7a5530', roughness: 0.60, metalness: 0.00 },
  { id: 'ew-int-mattress',       name: 'Matelas Blanc',            category: 'interior', color: '#f0ede8', roughness: 0.92, metalness: 0.00 },
  { id: 'ew-int-bedding-white',  name: 'Literie Blanche',          category: 'interior', color: '#fafaf8', roughness: 0.93, metalness: 0.00 },
  { id: 'ew-int-plant-pot-terracotta', name: 'Pot Terre Cuite',    category: 'interior', color: '#b86040', roughness: 0.85, metalness: 0.00 },
  { id: 'ew-int-plant-pot-white',name: 'Pot Cache-Pot Blanc',      category: 'interior', color: '#f4f2ee', roughness: 0.78, metalness: 0.00 },
  { id: 'ew-int-lamp-metal',     name: 'Lampe Pied Métal',         category: 'interior', color: '#3a3830', roughness: 0.45, metalness: 0.78 },
  { id: 'ew-int-lamp-shade',     name: 'Abat-Jour Blanc Lin',      category: 'interior', color: '#f0ece4', roughness: 0.88, metalness: 0.00, transparent: true, opacity: 0.88 },
  { id: 'ew-int-frame-black',    name: 'Cadre Photo Noir',         category: 'interior', color: '#1a1c1e', roughness: 0.55, metalness: 0.20 },
  { id: 'ew-int-frame-gold',     name: 'Cadre Photo Or',           category: 'interior', color: '#c9a84c', roughness: 0.35, metalness: 0.88 },
  { id: 'ew-int-door-interior',  name: 'Porte Intérieure Blanche', category: 'interior', color: '#f2f0ec', roughness: 0.78, metalness: 0.00 },
  { id: 'ew-int-door-wood-int',  name: 'Porte Intérieure Bois',    category: 'interior', color: '#a88050', roughness: 0.62, metalness: 0.00 },
  { id: 'ew-int-handle-gold',    name: 'Poignée Or Satiné',        category: 'interior', color: '#c9a84c', roughness: 0.32, metalness: 0.90 },
  { id: 'ew-int-handle-chrome',  name: 'Poignée Chrome',           category: 'interior', color: '#d4d8dc', roughness: 0.15, metalness: 0.96 },
  { id: 'ew-int-handle-matte',   name: 'Poignée Noir Mat',         category: 'interior', color: '#2a2c30', roughness: 0.45, metalness: 0.70 },
  { id: 'ew-int-switch-white',   name: 'Interrupteur Blanc',       category: 'interior', color: '#f4f2ee', roughness: 0.75, metalness: 0.00 },
  { id: 'ew-int-outlet-white',   name: 'Prise Électrique',         category: 'interior', color: '#f2f0ec', roughness: 0.78, metalness: 0.00 },
  { id: 'ew-int-ac-vent',        name: 'Grille Aération',          category: 'interior', color: '#e8e4dc', roughness: 0.65, metalness: 0.35 },
  { id: 'ew-int-smoke-detector', name: 'Détecteur Fumée',          category: 'interior', color: '#f0ece4', roughness: 0.70, metalness: 0.20 },
  { id: 'ew-int-thermostat',     name: 'Thermostat Intelligent',   category: 'interior', color: '#e8e4de', roughness: 0.50, metalness: 0.30, emissive: '#60d0ff', emissiveIntensity: 0.15 },
  { id: 'ew-int-tv-screen',      name: 'Télévision Écran',         category: 'interior', color: '#060810', roughness: 0.15, metalness: 0.20, emissive: '#102040', emissiveIntensity: 0.30 },
  { id: 'ew-int-speaker-fabric', name: 'Enceinte Tissu',           category: 'interior', color: '#3a3c40', roughness: 0.88, metalness: 0.10 },

  // ============================================================
  // 🚗 VOITURES — 80 matériaux
  // ============================================================
  { id: 'ew-car-paint-white',     name: 'Carrosserie Blanc Perle',  category: 'car', color: '#f4f2f0', roughness: 0.08, metalness: 0.20 },
  { id: 'ew-car-paint-black',     name: 'Carrosserie Noir Brillant',category: 'car', color: '#080a0c', roughness: 0.06, metalness: 0.25 },
  { id: 'ew-car-paint-red',       name: 'Carrosserie Rouge Ferrari', category: 'car', color: '#c0180c', roughness: 0.07, metalness: 0.22 },
  { id: 'ew-car-paint-blue',      name: 'Carrosserie Bleu Glacier', category: 'car', color: '#2a5080', roughness: 0.08, metalness: 0.22 },
  { id: 'ew-car-paint-silver',    name: 'Carrosserie Argent',       category: 'car', color: '#c0c8d0', roughness: 0.12, metalness: 0.65 },
  { id: 'ew-car-paint-grey',      name: 'Carrosserie Gris Titane',  category: 'car', color: '#6a7078', roughness: 0.10, metalness: 0.45 },
  { id: 'ew-car-paint-green',     name: 'Carrosserie Vert Forêt',   category: 'car', color: '#2a4a30', roughness: 0.09, metalness: 0.20 },
  { id: 'ew-car-paint-yellow',    name: 'Carrosserie Jaune Sport',  category: 'car', color: '#f0b800', roughness: 0.07, metalness: 0.20 },
  { id: 'ew-car-paint-orange',    name: 'Carrosserie Orange',       category: 'car', color: '#e06010', roughness: 0.08, metalness: 0.20 },
  { id: 'ew-car-paint-champagne', name: 'Carrosserie Champagne',    category: 'car', color: '#c8b890', roughness: 0.10, metalness: 0.30 },
  { id: 'ew-car-paint-midnight',  name: 'Carrosserie Bleu Nuit',    category: 'car', color: '#0a1020', roughness: 0.07, metalness: 0.28 },
  { id: 'ew-car-paint-bronze',    name: 'Carrosserie Bronze',       category: 'car', color: '#7a5028', roughness: 0.10, metalness: 0.40 },
  { id: 'ew-car-paint-matte-blk', name: 'Carrosserie Noir Mat',     category: 'car', color: '#1a1c1e', roughness: 0.55, metalness: 0.05 },
  { id: 'ew-car-paint-matte-grey',name: 'Carrosserie Gris Mat',     category: 'car', color: '#5a6068', roughness: 0.58, metalness: 0.05 },
  { id: 'ew-car-window',          name: 'Vitre Voiture Teintée',    category: 'car', color: '#1a2830', roughness: 0.04, metalness: 0.15, transparent: true, opacity: 0.60 },
  { id: 'ew-car-window-clear',    name: 'Pare-Brise Clair',         category: 'car', color: '#c0d8e8', roughness: 0.03, metalness: 0.12, transparent: true, opacity: 0.20 },
  { id: 'ew-car-chrome-trim',     name: 'Chrome Finition',          category: 'car', color: '#d8dce0', roughness: 0.08, metalness: 0.98 },
  { id: 'ew-car-chrome-wheel',    name: 'Jante Chrome',             category: 'car', color: '#d4d8dc', roughness: 0.10, metalness: 0.96 },
  { id: 'ew-car-wheel-black',     name: 'Jante Noire Sport',        category: 'car', color: '#1a1c20', roughness: 0.40, metalness: 0.75 },
  { id: 'ew-car-wheel-silver',    name: 'Jante Aluminium',          category: 'car', color: '#b0b8c0', roughness: 0.25, metalness: 0.88 },
  { id: 'ew-car-wheel-gold',      name: 'Jante Or',                 category: 'car', color: '#c9a84c', roughness: 0.20, metalness: 0.90 },
  { id: 'ew-car-tire',            name: 'Pneu Rubber',              category: 'car', color: '#1a1c1e', roughness: 0.92, metalness: 0.00 },
  { id: 'ew-car-brake-caliper-red',name: 'Étrier Frein Rouge',      category: 'car', color: '#c01808', roughness: 0.55, metalness: 0.30 },
  { id: 'ew-car-brake-caliper-blk',name: 'Étrier Frein Noir',       category: 'car', color: '#1a1c20', roughness: 0.50, metalness: 0.35 },
  { id: 'ew-car-interior-black',  name: 'Intérieur Cuir Noir',      category: 'car', color: '#141618', roughness: 0.38, metalness: 0.05 },
  { id: 'ew-car-interior-beige',  name: 'Intérieur Cuir Beige',     category: 'car', color: '#c8aa80', roughness: 0.40, metalness: 0.04 },
  { id: 'ew-car-interior-red',    name: 'Intérieur Cuir Rouge',     category: 'car', color: '#6a1c14', roughness: 0.40, metalness: 0.04 },
  { id: 'ew-car-dashboard',       name: 'Tableau de Bord',          category: 'car', color: '#1c1e22', roughness: 0.55, metalness: 0.15, emissive: '#102040', emissiveIntensity: 0.10 },
  { id: 'ew-car-dashboard-wood',  name: 'Tableau de Bord Bois',     category: 'car', color: '#5a3820', roughness: 0.35, metalness: 0.05 },
  { id: 'ew-car-seat-alcantara',  name: 'Siège Alcantara',          category: 'car', color: '#2a2c30', roughness: 0.85, metalness: 0.00 },
  { id: 'ew-car-seat-fabric',     name: 'Siège Tissu',              category: 'car', color: '#4a5058', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-car-carpet',          name: 'Tapis Sol Voiture',        category: 'car', color: '#1a1c20', roughness: 0.92, metalness: 0.00 },
  { id: 'ew-car-headlight',       name: 'Phare LED',                category: 'car', color: '#f8f4e8', roughness: 0.12, metalness: 0.40, emissive: '#ffffff', emissiveIntensity: 1.50 },
  { id: 'ew-car-taillight-red',   name: 'Feu Arrière Rouge',        category: 'car', color: '#c00808', roughness: 0.15, metalness: 0.20, emissive: '#ff0000', emissiveIntensity: 0.80 },
  { id: 'ew-car-taillight-white', name: 'Clignotant Blanc',         category: 'car', color: '#f0e8d0', roughness: 0.15, metalness: 0.20, emissive: '#ffee88', emissiveIntensity: 0.60 },
  { id: 'ew-car-grill-black',     name: 'Calandre Noir Brillant',   category: 'car', color: '#0a0c0e', roughness: 0.15, metalness: 0.50 },
  { id: 'ew-car-grill-chrome',    name: 'Calandre Chrome',          category: 'car', color: '#d0d4d8', roughness: 0.10, metalness: 0.95 },
  { id: 'ew-car-bumper-painted',  name: 'Pare-Choc Peint',          category: 'car', color: '#1a1c1e', roughness: 0.12, metalness: 0.25 },
  { id: 'ew-car-bumper-rubber',   name: 'Pare-Choc Plastique',      category: 'car', color: '#2a2c30', roughness: 0.75, metalness: 0.00 },
  { id: 'ew-car-exhaust',         name: 'Silencieux Inox',          category: 'car', color: '#c0c8d0', roughness: 0.35, metalness: 0.88 },
  { id: 'ew-car-roof-fabric',     name: 'Toit Tissu Cabriolet',     category: 'car', color: '#2a2c30', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-car-undercarriage',   name: 'Dessous Châssis',          category: 'car', color: '#2a2c2e', roughness: 0.82, metalness: 0.30 },
  { id: 'ew-car-engine-block',    name: 'Bloc Moteur',              category: 'car', color: '#3a3c40', roughness: 0.60, metalness: 0.50 },
  { id: 'ew-car-engine-cover',    name: 'Cache Moteur',             category: 'car', color: '#1a1c1e', roughness: 0.45, metalness: 0.40 },
  { id: 'ew-car-truck-bed',       name: 'Plateau Camionnette',      category: 'car', color: '#2a2c30', roughness: 0.75, metalness: 0.35 },
  { id: 'ew-car-van-white',       name: 'Fourgon Blanc Commercial', category: 'car', color: '#eeece8', roughness: 0.55, metalness: 0.15 },
  { id: 'ew-car-suv-black',       name: 'VUS Noir',                 category: 'car', color: '#0e1012', roughness: 0.08, metalness: 0.28 },
  { id: 'ew-car-police',          name: 'Voiture Police',           category: 'car', color: '#2a3848', roughness: 0.20, metalness: 0.30 },
  { id: 'ew-car-ambulance',       name: 'Ambulance Blanc',          category: 'car', color: '#f0eeea', roughness: 0.30, metalness: 0.20 },
  { id: 'ew-car-taxi-yellow',     name: 'Taxi Jaune',               category: 'car', color: '#f0b800', roughness: 0.12, metalness: 0.20 },
  { id: 'ew-car-school-bus',      name: 'Autobus Scolaire Jaune',   category: 'car', color: '#f5b800', roughness: 0.30, metalness: 0.20 },
  { id: 'ew-car-firetruck-red',   name: 'Camion Incendie Rouge',    category: 'car', color: '#b81010', roughness: 0.20, metalness: 0.25 },
  { id: 'ew-car-rust',            name: 'Rouille Carrosserie',      category: 'car', color: '#7a3018', roughness: 0.90, metalness: 0.15 },
  { id: 'ew-car-wrap-camo',       name: 'Wrap Camouflage',          category: 'car', color: '#4a5838', roughness: 0.60, metalness: 0.05 },
  { id: 'ew-car-wrap-carbon',     name: 'Wrap Carbon Look',         category: 'car', color: '#1a1c20', roughness: 0.30, metalness: 0.15 },
  { id: 'ew-car-neon-underglow',  name: 'Néon Sous Caisse',         category: 'car', color: '#00e8ff', roughness: 0.20, metalness: 0.10, emissive: '#00e8ff', emissiveIntensity: 1.50 },
  { id: 'ew-car-license-plate',   name: 'Plaque Immatriculation',   category: 'car', color: '#d8e0d0', roughness: 0.60, metalness: 0.30 },
  { id: 'ew-car-side-mirror',     name: 'Rétroviseur',              category: 'car', color: '#1a1c1e', roughness: 0.40, metalness: 0.50 },
  { id: 'ew-car-wiper',           name: 'Essuie-Glace',             category: 'car', color: '#1a1c1e', roughness: 0.80, metalness: 0.30 },
  { id: 'ew-car-antenna',         name: 'Antenne',                  category: 'car', color: '#2a2c30', roughness: 0.45, metalness: 0.70 },
  { id: 'ew-car-spoiler-carbon',  name: 'Aileron Carbon',           category: 'car', color: '#1a1c20', roughness: 0.28, metalness: 0.18 },
  { id: 'ew-car-spoiler-white',   name: 'Aileron Blanc',            category: 'car', color: '#f2f0ec', roughness: 0.10, metalness: 0.22 },
  { id: 'ew-car-decal-stripe',    name: 'Décoration Bande Racing',  category: 'car', color: '#c01010', roughness: 0.30, metalness: 0.10 },
  { id: 'ew-car-seat-heated',     name: 'Siège Chauffant Luxe',     category: 'car', color: '#1e2028', roughness: 0.38, metalness: 0.08, emissive: '#ff4400', emissiveIntensity: 0.05 },
  { id: 'ew-car-speedometer',     name: 'Compteur Vitesse',         category: 'car', color: '#0a0c10', roughness: 0.20, metalness: 0.30, emissive: '#3060ff', emissiveIntensity: 0.40 },
  { id: 'ew-car-steering-leather',name: 'Volant Cuir',              category: 'car', color: '#1c1818', roughness: 0.42, metalness: 0.05 },
  { id: 'ew-car-gear-shift',      name: 'Levier Vitesse',           category: 'car', color: '#2a2428', roughness: 0.38, metalness: 0.35 },
  { id: 'ew-car-floor-mat',       name: 'Tapis Caoutchouc',         category: 'car', color: '#181a1e', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-car-charger-ev',      name: 'Chargeur VÉ Connexion',    category: 'car', color: '#2a3040', roughness: 0.50, metalness: 0.40, emissive: '#00c860', emissiveIntensity: 0.30 },

  // ============================================================
  // 👔 VÊTEMENTS — 80 matériaux
  // ============================================================
  { id: 'ew-cloth-cotton-white',  name: 'Coton Blanc T-Shirt',      category: 'clothes', color: '#f4f2ee', roughness: 0.92, metalness: 0.00 },
  { id: 'ew-cloth-cotton-black',  name: 'Coton Noir',               category: 'clothes', color: '#141618', roughness: 0.90, metalness: 0.00 },
  { id: 'ew-cloth-cotton-grey',   name: 'Coton Gris Chiné',         category: 'clothes', color: '#8090a0', roughness: 0.91, metalness: 0.00 },
  { id: 'ew-cloth-cotton-navy',   name: 'Coton Bleu Marine',        category: 'clothes', color: '#1a2848', roughness: 0.90, metalness: 0.00 },
  { id: 'ew-cloth-cotton-red',    name: 'Coton Rouge',              category: 'clothes', color: '#b01818', roughness: 0.91, metalness: 0.00 },
  { id: 'ew-cloth-denim-blue',    name: 'Denim Bleu Jean',          category: 'clothes', color: '#3a5878', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-cloth-denim-black',   name: 'Denim Noir',               category: 'clothes', color: '#1e2028', roughness: 0.87, metalness: 0.00 },
  { id: 'ew-cloth-denim-faded',   name: 'Denim Délavé',             category: 'clothes', color: '#7090a8', roughness: 0.90, metalness: 0.00 },
  { id: 'ew-cloth-wool-grey',     name: 'Laine Gris Manteau',       category: 'clothes', color: '#6a7078', roughness: 0.93, metalness: 0.00 },
  { id: 'ew-cloth-wool-camel',    name: 'Laine Camel',              category: 'clothes', color: '#c89858', roughness: 0.92, metalness: 0.00 },
  { id: 'ew-cloth-wool-navy',     name: 'Laine Marine',             category: 'clothes', color: '#1a2840', roughness: 0.92, metalness: 0.00 },
  { id: 'ew-cloth-leather-black', name: 'Cuir Veste Noir',          category: 'clothes', color: '#0e1012', roughness: 0.35, metalness: 0.08 },
  { id: 'ew-cloth-leather-brown', name: 'Cuir Brun Naturel',        category: 'clothes', color: '#6a4020', roughness: 0.38, metalness: 0.06 },
  { id: 'ew-cloth-leather-red',   name: 'Cuir Rouge Vif',           category: 'clothes', color: '#8c1c14', roughness: 0.36, metalness: 0.07 },
  { id: 'ew-cloth-leather-white', name: 'Cuir Blanc Luxe',          category: 'clothes', color: '#f2eee8', roughness: 0.32, metalness: 0.06 },
  { id: 'ew-cloth-velvet-black',  name: 'Velours Noir Robe',        category: 'clothes', color: '#121416', roughness: 0.78, metalness: 0.00 },
  { id: 'ew-cloth-velvet-purple', name: 'Velours Violet Royal',     category: 'clothes', color: '#3a1860', roughness: 0.76, metalness: 0.00 },
  { id: 'ew-cloth-velvet-green',  name: 'Velours Vert Émeraude',    category: 'clothes', color: '#1a5038', roughness: 0.77, metalness: 0.00 },
  { id: 'ew-cloth-silk-white',    name: 'Soie Blanche Chemise',     category: 'clothes', color: '#f8f6f4', roughness: 0.15, metalness: 0.08 },
  { id: 'ew-cloth-silk-black',    name: 'Soie Noire',               category: 'clothes', color: '#141618', roughness: 0.12, metalness: 0.10 },
  { id: 'ew-cloth-silk-red',      name: 'Soie Rouge Robe',          category: 'clothes', color: '#a01818', roughness: 0.14, metalness: 0.08 },
  { id: 'ew-cloth-satin-white',   name: 'Satin Blanc Mariage',      category: 'clothes', color: '#faf8f4', roughness: 0.12, metalness: 0.12 },
  { id: 'ew-cloth-satin-gold',    name: 'Satin Or',                 category: 'clothes', color: '#c9a840', roughness: 0.14, metalness: 0.30 },
  { id: 'ew-cloth-linen-beige',   name: 'Lin Beige Estival',        category: 'clothes', color: '#d0c0a0', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-cloth-linen-white',   name: 'Lin Blanc Naturel',        category: 'clothes', color: '#f0ece4', roughness: 0.89, metalness: 0.00 },
  { id: 'ew-cloth-polyester',     name: 'Polyester Sport',          category: 'clothes', color: '#3a5c8a', roughness: 0.60, metalness: 0.05 },
  { id: 'ew-cloth-nylon-jacket',  name: 'Nylon Veste Sport',        category: 'clothes', color: '#1a2840', roughness: 0.45, metalness: 0.10 },
  { id: 'ew-cloth-fleece-grey',   name: 'Polaire Gris',             category: 'clothes', color: '#8090a0', roughness: 0.95, metalness: 0.00 },
  { id: 'ew-cloth-fleece-black',  name: 'Polaire Noire',            category: 'clothes', color: '#1c1e22', roughness: 0.94, metalness: 0.00 },
  { id: 'ew-cloth-down-jacket',   name: 'Doudoune Hiver',           category: 'clothes', color: '#1a2440', roughness: 0.80, metalness: 0.05 },
  { id: 'ew-cloth-down-black',    name: 'Doudoune Noire',           category: 'clothes', color: '#141618', roughness: 0.82, metalness: 0.05 },
  { id: 'ew-cloth-raincoat',      name: 'Imperméable',              category: 'clothes', color: '#1a3060', roughness: 0.25, metalness: 0.10 },
  { id: 'ew-cloth-raincoat-yellow', name: 'Imperméable Jaune',      category: 'clothes', color: '#d4a800', roughness: 0.28, metalness: 0.08 },
  { id: 'ew-cloth-suit-black',    name: 'Complet Noir',             category: 'clothes', color: '#141618', roughness: 0.75, metalness: 0.03 },
  { id: 'ew-cloth-suit-grey',     name: 'Complet Gris',             category: 'clothes', color: '#5a6068', roughness: 0.78, metalness: 0.03 },
  { id: 'ew-cloth-suit-navy',     name: 'Complet Marine',           category: 'clothes', color: '#1a2840', roughness: 0.76, metalness: 0.03 },
  { id: 'ew-cloth-dress-black',   name: 'Robe Noire',               category: 'clothes', color: '#0e1012', roughness: 0.70, metalness: 0.03 },
  { id: 'ew-cloth-dress-red',     name: 'Robe Rouge',               category: 'clothes', color: '#980c0c', roughness: 0.68, metalness: 0.03 },
  { id: 'ew-cloth-dress-white',   name: 'Robe Blanche',             category: 'clothes', color: '#f8f6f2', roughness: 0.70, metalness: 0.02 },
  { id: 'ew-cloth-hoodie-grey',   name: 'Hoodie Gris',              category: 'clothes', color: '#7a8088', roughness: 0.90, metalness: 0.00 },
  { id: 'ew-cloth-hoodie-black',  name: 'Hoodie Noir',              category: 'clothes', color: '#141618', roughness: 0.90, metalness: 0.00 },
  { id: 'ew-cloth-shorts-khaki',  name: 'Short Kaki',               category: 'clothes', color: '#8a8050', roughness: 0.86, metalness: 0.00 },
  { id: 'ew-cloth-cargo-green',   name: 'Cargo Militaire',          category: 'clothes', color: '#4a5838', roughness: 0.87, metalness: 0.00 },
  { id: 'ew-cloth-uniform-police',name: 'Uniforme Police',          category: 'clothes', color: '#2a3040', roughness: 0.82, metalness: 0.05 },
  { id: 'ew-cloth-uniform-fire',  name: 'Uniforme Pompier',         category: 'clothes', color: '#8a2810', roughness: 0.78, metalness: 0.10 },
  { id: 'ew-cloth-uniform-medical',name: 'Uniforme Médical',        category: 'clothes', color: '#c8e4e0', roughness: 0.80, metalness: 0.00 },
  { id: 'ew-cloth-uniform-chef',  name: 'Veste Chef Blanche',       category: 'clothes', color: '#f0ece8', roughness: 0.82, metalness: 0.00 },
  { id: 'ew-cloth-uniform-worker',name: 'Uniforme Ouvrier',         category: 'clothes', color: '#3a4858', roughness: 0.84, metalness: 0.05 },
  { id: 'ew-cloth-reflective',    name: 'Veste Réfléchissante',     category: 'clothes', color: '#f0a800', roughness: 0.65, metalness: 0.20, emissive: '#f0a800', emissiveIntensity: 0.20 },
  { id: 'ew-cloth-gloves-leather',name: 'Gants Cuir',               category: 'clothes', color: '#3a2018', roughness: 0.40, metalness: 0.05 },
  { id: 'ew-cloth-gloves-rubber', name: 'Gants Caoutchouc',         category: 'clothes', color: '#1a3028', roughness: 0.55, metalness: 0.05 },
  { id: 'ew-cloth-hat-wool',      name: 'Tuque Laine',              category: 'clothes', color: '#3a3038', roughness: 0.93, metalness: 0.00 },
  { id: 'ew-cloth-hat-baseball',  name: 'Casquette Baseball',       category: 'clothes', color: '#1a1c1e', roughness: 0.80, metalness: 0.00 },
  { id: 'ew-cloth-hat-hard',      name: 'Casque Chantier Jaune',    category: 'clothes', color: '#f0b800', roughness: 0.60, metalness: 0.10 },
  { id: 'ew-cloth-scarf-grey',    name: 'Écharpe Grise',            category: 'clothes', color: '#7a8088', roughness: 0.93, metalness: 0.00 },
  { id: 'ew-cloth-boot-leather',  name: 'Botte Cuir Brun',          category: 'clothes', color: '#5a3818', roughness: 0.48, metalness: 0.05 },
  { id: 'ew-cloth-boot-rubber',   name: 'Botte Caoutchouc Noire',   category: 'clothes', color: '#1a1c1e', roughness: 0.62, metalness: 0.05 },
  { id: 'ew-cloth-shoe-white',    name: 'Soulier Blanc Cuir',       category: 'clothes', color: '#f2f0ec', roughness: 0.38, metalness: 0.05 },
  { id: 'ew-cloth-sneaker-white', name: 'Sneaker Blanc',            category: 'clothes', color: '#f4f2ee', roughness: 0.55, metalness: 0.05 },
  { id: 'ew-cloth-sneaker-black', name: 'Sneaker Noir',             category: 'clothes', color: '#141618', roughness: 0.58, metalness: 0.05 },
  { id: 'ew-cloth-belt-leather',  name: 'Ceinture Cuir',            category: 'clothes', color: '#2a1810', roughness: 0.42, metalness: 0.05 },
  { id: 'ew-cloth-belt-buckle',   name: 'Boucle Ceinture Or',       category: 'clothes', color: '#c0a040', roughness: 0.25, metalness: 0.90 },
  { id: 'ew-cloth-tie-black',     name: 'Cravate Noire',            category: 'clothes', color: '#0e1012', roughness: 0.28, metalness: 0.08 },
  { id: 'ew-cloth-tie-red',       name: 'Cravate Rouge',            category: 'clothes', color: '#8c1010', roughness: 0.25, metalness: 0.08 },
  { id: 'ew-cloth-watch-steel',   name: 'Montre Acier',             category: 'clothes', color: '#c0c8d0', roughness: 0.22, metalness: 0.92 },
  { id: 'ew-cloth-watch-gold',    name: 'Montre Or Luxe',           category: 'clothes', color: '#c9a84c', roughness: 0.18, metalness: 0.95 },
  { id: 'ew-cloth-sunglasses',    name: 'Lunettes Soleil',          category: 'clothes', color: '#0a0c0e', roughness: 0.20, metalness: 0.40, transparent: true, opacity: 0.70 },
  { id: 'ew-cloth-necklace-gold', name: 'Collier Or',               category: 'clothes', color: '#c9a840', roughness: 0.20, metalness: 0.95 },
  { id: 'ew-cloth-ring-gold',     name: 'Bague Or',                 category: 'clothes', color: '#c8a838', roughness: 0.18, metalness: 0.96 },
  { id: 'ew-cloth-earring-gold',  name: 'Boucle Oreille Or',        category: 'clothes', color: '#c9a84c', roughness: 0.20, metalness: 0.95 },
  { id: 'ew-cloth-bag-leather',   name: 'Sac Cuir Brun',            category: 'clothes', color: '#5a3820', roughness: 0.42, metalness: 0.05 },
  { id: 'ew-cloth-bag-black',     name: 'Sac Noir Luxe',            category: 'clothes', color: '#0e1012', roughness: 0.38, metalness: 0.08 },
  { id: 'ew-cloth-backpack',      name: 'Sac à Dos Nylon',          category: 'clothes', color: '#2a3040', roughness: 0.78, metalness: 0.05 },
  { id: 'ew-cloth-wetsuit',       name: 'Combinaison Néoprène',     category: 'clothes', color: '#1a1c22', roughness: 0.65, metalness: 0.08 },
  { id: 'ew-cloth-spacesuit',     name: 'Combinaison Spatiale',     category: 'clothes', color: '#e8e4dc', roughness: 0.70, metalness: 0.30 },

  // ============================================================
  // 💼 EMPLOIS / OUTILS — 80 matériaux
  // ============================================================
  { id: 'ew-job-metal-chrome',    name: 'Chrome Industriel',        category: 'job', color: '#d4d8dc', roughness: 0.18, metalness: 0.96 },
  { id: 'ew-job-metal-steel',     name: 'Acier Brossé Industriel',  category: 'job', color: '#9aa0a8', roughness: 0.38, metalness: 0.94 },
  { id: 'ew-job-metal-iron',      name: 'Fonte Grise',              category: 'job', color: '#5a5c60', roughness: 0.60, metalness: 0.80 },
  { id: 'ew-job-metal-aluminum',  name: 'Aluminium Brut',           category: 'job', color: '#c0c8d0', roughness: 0.35, metalness: 0.88 },
  { id: 'ew-job-metal-brass',     name: 'Laiton',                   category: 'job', color: '#b89940', roughness: 0.30, metalness: 0.88 },
  { id: 'ew-job-metal-titanium',  name: 'Titane',                   category: 'job', color: '#8a9098', roughness: 0.32, metalness: 0.92 },
  { id: 'ew-job-metal-gold',      name: 'Or 24k',                   category: 'job', color: '#c9a840', roughness: 0.15, metalness: 0.98 },
  { id: 'ew-job-metal-copper',    name: 'Cuivre Industriel',        category: 'job', color: '#b06830', roughness: 0.40, metalness: 0.85 },
  { id: 'ew-job-plastic-hard',    name: 'Plastique Dur Gris',       category: 'job', color: '#6a7078', roughness: 0.70, metalness: 0.00 },
  { id: 'ew-job-plastic-black',   name: 'Plastique Noir ABS',       category: 'job', color: '#1a1c20', roughness: 0.65, metalness: 0.00 },
  { id: 'ew-job-plastic-yellow',  name: 'Plastique Jaune Sécurité', category: 'job', color: '#e8a800', roughness: 0.68, metalness: 0.00 },
  { id: 'ew-job-plastic-red',     name: 'Plastique Rouge Signal',   category: 'job', color: '#c01010', roughness: 0.65, metalness: 0.00 },
  { id: 'ew-job-rubber-black',    name: 'Caoutchouc Noir',          category: 'job', color: '#1a1c1e', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-job-rubber-grip',     name: 'Poignée Caoutchouc',       category: 'job', color: '#2a2c30', roughness: 0.90, metalness: 0.00 },
  { id: 'ew-job-wood-tool',       name: 'Manche Bois Outil',        category: 'job', color: '#b08050', roughness: 0.68, metalness: 0.00 },
  { id: 'ew-job-carbon-fiber',    name: 'Fibre de Carbone',         category: 'job', color: '#1a1c20', roughness: 0.28, metalness: 0.18 },
  { id: 'ew-job-fiberglass',      name: 'Fibre de Verre',           category: 'job', color: '#d0c8b0', roughness: 0.65, metalness: 0.05 },
  { id: 'ew-job-paint-industrial',name: 'Peinture Industrielle',    category: 'job', color: '#2a4060', roughness: 0.55, metalness: 0.20 },
  { id: 'ew-job-pipe-steel',      name: 'Tuyau Acier',              category: 'job', color: '#8a9098', roughness: 0.50, metalness: 0.78 },
  { id: 'ew-job-pipe-pvc',        name: 'Tuyau PVC Blanc',          category: 'job', color: '#e8e4dc', roughness: 0.65, metalness: 0.00 },
  { id: 'ew-job-pipe-orange',     name: 'Tuyau Orange Électrique',  category: 'job', color: '#e06020', roughness: 0.62, metalness: 0.00 },
  { id: 'ew-job-wire-copper',     name: 'Câble Cuivre Dénudé',      category: 'job', color: '#b06830', roughness: 0.42, metalness: 0.85 },
  { id: 'ew-job-wire-insulated',  name: 'Câble Isolé Noir',         category: 'job', color: '#1a1c1e', roughness: 0.72, metalness: 0.00 },
  { id: 'ew-job-concrete-floor',  name: 'Sol Usine Béton',          category: 'job', color: '#9a9590', roughness: 0.90, metalness: 0.00 },
  { id: 'ew-job-floor-epoxy-grey',name: 'Époxy Industriel Gris',    category: 'job', color: '#8a9098', roughness: 0.25, metalness: 0.10 },
  { id: 'ew-job-floor-checker',   name: 'Sol Damier Sécurité',      category: 'job', color: '#f0a800', roughness: 0.55, metalness: 0.15 },
  { id: 'ew-job-safety-tape',     name: 'Ruban Sécurité Jaune-Noir',category: 'job', color: '#e0a000', roughness: 0.60, metalness: 0.00 },
  { id: 'ew-job-safety-net',      name: 'Filet Sécurité Orange',    category: 'job', color: '#e05010', roughness: 0.85, metalness: 0.00 },
  { id: 'ew-job-barrier-cone',    name: 'Cône Sécurité Orange',     category: 'job', color: '#e84800', roughness: 0.65, metalness: 0.00 },
  { id: 'ew-job-scaffolding',     name: 'Échafaudage Métal',        category: 'job', color: '#7a8088', roughness: 0.50, metalness: 0.70 },
  { id: 'ew-job-tarpaulin-blue',  name: 'Bâche Bleue',              category: 'job', color: '#1a4870', roughness: 0.75, metalness: 0.00, transparent: true, opacity: 0.90 },
  { id: 'ew-job-tarpaulin-green', name: 'Bâche Verte',              category: 'job', color: '#1a4828', roughness: 0.75, metalness: 0.00, transparent: true, opacity: 0.90 },
  { id: 'ew-job-welding-mask',    name: 'Masque Soudeur',           category: 'job', color: '#2a2820', roughness: 0.65, metalness: 0.30 },
  { id: 'ew-job-drill-metal',     name: 'Perceuse Métal',           category: 'job', color: '#2a2830', roughness: 0.45, metalness: 0.65 },
  { id: 'ew-job-saw-blade',       name: 'Lame de Scie',             category: 'job', color: '#8a9098', roughness: 0.30, metalness: 0.90 },
  { id: 'ew-job-hammer-head',     name: 'Marteau Métal',            category: 'job', color: '#6a7078', roughness: 0.48, metalness: 0.80 },
  { id: 'ew-job-wrench',          name: 'Clé Anglaise',             category: 'job', color: '#7a8090', roughness: 0.40, metalness: 0.82 },
  { id: 'ew-job-screwdriver',     name: 'Tournevis',                category: 'job', color: '#c01010', roughness: 0.55, metalness: 0.20 },
  { id: 'ew-job-level',           name: 'Niveau à Bulle',           category: 'job', color: '#2a2828', roughness: 0.50, metalness: 0.40 },
  { id: 'ew-job-measuring-tape',  name: 'Ruban à Mesurer',          category: 'job', color: '#c09000', roughness: 0.60, metalness: 0.30 },
  { id: 'ew-job-bucket-paint',    name: 'Seau Peinture',            category: 'job', color: '#d8d4cc', roughness: 0.65, metalness: 0.30 },
  { id: 'ew-job-paintbrush',      name: 'Pinceau Bois',             category: 'job', color: '#9a7050', roughness: 0.72, metalness: 0.00 },
  { id: 'ew-job-ladder-aluminum', name: 'Échelle Aluminium',        category: 'job', color: '#c0c8d0', roughness: 0.45, metalness: 0.78 },
  { id: 'ew-job-toolbox-red',     name: 'Boîte à Outils Rouge',     category: 'job', color: '#b01010', roughness: 0.55, metalness: 0.45 },
  { id: 'ew-job-helmet-white',    name: 'Casque Sécurité Blanc',    category: 'job', color: '#f0ede8', roughness: 0.55, metalness: 0.10 },
  { id: 'ew-job-helmet-yellow',   name: 'Casque Sécurité Jaune',    category: 'job', color: '#e8b000', roughness: 0.55, metalness: 0.10 },
  { id: 'ew-job-vest-orange',     name: 'Gilet Orange Fluorescent', category: 'job', color: '#ff5000', roughness: 0.72, metalness: 0.00, emissive: '#ff4000', emissiveIntensity: 0.12 },
  { id: 'ew-job-gloves-work',     name: 'Gants Travail Cuir',       category: 'job', color: '#6a4828', roughness: 0.65, metalness: 0.00 },
  { id: 'ew-job-boots-steel',     name: 'Bottes Sécurité Acier',    category: 'job', color: '#2a2c30', roughness: 0.62, metalness: 0.20 },
  { id: 'ew-job-server-rack',     name: 'Serveur Informatique',     category: 'job', color: '#1a1c20', roughness: 0.40, metalness: 0.60, emissive: '#002040', emissiveIntensity: 0.10 },
  { id: 'ew-job-circuit-board',   name: 'Circuit Imprimé',          category: 'job', color: '#1a3820', roughness: 0.55, metalness: 0.30, emissive: '#003000', emissiveIntensity: 0.08 },
  { id: 'ew-job-computer-desk',   name: 'Bureau Informatique',      category: 'job', color: '#1e2028', roughness: 0.45, metalness: 0.50 },
  { id: 'ew-job-whiteboard',      name: 'Tableau Blanc Bureau',     category: 'job', color: '#f8f6f2', roughness: 0.35, metalness: 0.05 },
  { id: 'ew-job-desk-wood',       name: 'Bureau Bois Professionnel',category: 'job', color: '#8a6040', roughness: 0.52, metalness: 0.00 },
  { id: 'ew-job-desk-steel',      name: 'Bureau Métal Industriel',  category: 'job', color: '#7a8088', roughness: 0.45, metalness: 0.70 },
  { id: 'ew-job-chair-office',    name: 'Chaise Bureau Noir',       category: 'job', color: '#1a1c20', roughness: 0.68, metalness: 0.20 },
  { id: 'ew-job-filing-cabinet',  name: 'Classeur Métal',           category: 'job', color: '#8a9098', roughness: 0.50, metalness: 0.65 },
  { id: 'ew-job-hospital-green',  name: 'Mur Hôpital Vert',         category: 'job', color: '#c0d4c8', roughness: 0.82, metalness: 0.00 },
  { id: 'ew-job-hospital-white',  name: 'Équipement Médical Blanc', category: 'job', color: '#f2f0ec', roughness: 0.40, metalness: 0.15 },
  { id: 'ew-job-restaurant-steel',name: 'Cuisine Restaurant Inox',  category: 'job', color: '#b0b8c0', roughness: 0.28, metalness: 0.92 },
  { id: 'ew-job-road-marking',    name: 'Marquage Routier Blanc',   category: 'job', color: '#e8e4d8', roughness: 0.70, metalness: 0.00 },
  { id: 'ew-job-road-marking-yellow', name: 'Marquage Routier Jaune', category: 'job', color: '#e0b000', roughness: 0.68, metalness: 0.00 },
  { id: 'ew-job-manhole-steel',   name: 'Regard Égout Métal',       category: 'job', color: '#5a6068', roughness: 0.62, metalness: 0.70 },
  { id: 'ew-job-fire-extinguisher',name: 'Extincteur Rouge',        category: 'job', color: '#c01010', roughness: 0.45, metalness: 0.55 },
  { id: 'ew-job-first-aid',       name: 'Trousse Premiers Soins',   category: 'job', color: '#d01010', roughness: 0.60, metalness: 0.15 },
  { id: 'ew-job-cash-register',   name: 'Caisse Enregistreuse',     category: 'job', color: '#2a2c30', roughness: 0.45, metalness: 0.50, emissive: '#102040', emissiveIntensity: 0.08 },
  { id: 'ew-job-shopping-cart',   name: 'Panier Épicerie',          category: 'job', color: '#c0c8d0', roughness: 0.45, metalness: 0.70 },
  { id: 'ew-job-pallet-wood',     name: 'Palette Bois',             category: 'job', color: '#b08050', roughness: 0.85, metalness: 0.00 },
  { id: 'ew-job-warehouse-floor', name: 'Sol Entrepôt',             category: 'job', color: '#9a9590', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-job-forklift-yellow', name: 'Chariot Élévateur',        category: 'job', color: '#e0a800', roughness: 0.50, metalness: 0.35 },
  { id: 'ew-job-conveyor',        name: 'Convoyeur Industriel',     category: 'job', color: '#4a4c50', roughness: 0.55, metalness: 0.55 },
  { id: 'ew-job-tank-steel',      name: 'Réservoir Inox',           category: 'job', color: '#b0b8c0', roughness: 0.30, metalness: 0.88 },
  { id: 'ew-job-generator',       name: 'Génératrice Industrielle', category: 'job', color: '#3a4048', roughness: 0.55, metalness: 0.55 },
  { id: 'ew-job-solar-farm',      name: 'Parc Solaire Industriel',  category: 'job', color: '#1a2030', roughness: 0.28, metalness: 0.35, emissive: '#002040', emissiveIntensity: 0.08 },
  { id: 'ew-job-wind-turbine',    name: 'Éolienne Blanche',         category: 'job', color: '#e8e4dc', roughness: 0.50, metalness: 0.25 },

  // ============================================================
  // ✨ EFFETS VISUELS — 60 matériaux
  // ============================================================
  { id: 'ew-vfx-neon-cyan',       name: 'Néon Cyan Ether',          category: 'vfx', color: '#00e8ff', roughness: 0.20, metalness: 0.15, emissive: '#00e8ff', emissiveIntensity: 1.30 },
  { id: 'ew-vfx-neon-blue',       name: 'Néon Bleu',                category: 'vfx', color: '#0060ff', roughness: 0.20, metalness: 0.15, emissive: '#0060ff', emissiveIntensity: 1.30 },
  { id: 'ew-vfx-neon-red',        name: 'Néon Rouge',               category: 'vfx', color: '#ff1010', roughness: 0.20, metalness: 0.15, emissive: '#ff1010', emissiveIntensity: 1.30 },
  { id: 'ew-vfx-neon-green',      name: 'Néon Vert Matrix',         category: 'vfx', color: '#00ff40', roughness: 0.20, metalness: 0.15, emissive: '#00ff40', emissiveIntensity: 1.30 },
  { id: 'ew-vfx-neon-purple',     name: 'Néon Violet',              category: 'vfx', color: '#8800ff', roughness: 0.20, metalness: 0.15, emissive: '#8800ff', emissiveIntensity: 1.30 },
  { id: 'ew-vfx-neon-pink',       name: 'Néon Rose',                category: 'vfx', color: '#ff0080', roughness: 0.20, metalness: 0.15, emissive: '#ff0080', emissiveIntensity: 1.30 },
  { id: 'ew-vfx-neon-orange',     name: 'Néon Orange',              category: 'vfx', color: '#ff6000', roughness: 0.20, metalness: 0.15, emissive: '#ff6000', emissiveIntensity: 1.30 },
  { id: 'ew-vfx-neon-white',      name: 'Néon Blanc LED',           category: 'vfx', color: '#ffffff', roughness: 0.20, metalness: 0.15, emissive: '#ffffff', emissiveIntensity: 1.20 },
  { id: 'ew-vfx-neon-warm',       name: 'Néon Blanc Chaud',         category: 'vfx', color: '#ffd39a', roughness: 0.20, metalness: 0.10, emissive: '#ffd39a', emissiveIntensity: 1.25 },
  { id: 'ew-vfx-neon-gold',       name: 'Néon Or',                  category: 'vfx', color: '#ffcc00', roughness: 0.20, metalness: 0.20, emissive: '#ffcc00', emissiveIntensity: 1.20 },
  { id: 'ew-vfx-plasma-blue',     name: 'Plasma Bleu',              category: 'vfx', color: '#1040ff', roughness: 0.15, metalness: 0.20, emissive: '#1040ff', emissiveIntensity: 2.00, transparent: true, opacity: 0.75 },
  { id: 'ew-vfx-plasma-violet',   name: 'Plasma Violet',            category: 'vfx', color: '#6000ff', roughness: 0.15, metalness: 0.20, emissive: '#6000ff', emissiveIntensity: 2.00, transparent: true, opacity: 0.70 },
  { id: 'ew-vfx-plasma-green',    name: 'Plasma Vert',              category: 'vfx', color: '#00ff60', roughness: 0.15, metalness: 0.20, emissive: '#00ff60', emissiveIntensity: 2.00, transparent: true, opacity: 0.70 },
  { id: 'ew-vfx-hologram',        name: 'Hologramme Cyan',          category: 'vfx', color: '#00e8ff', roughness: 0.10, metalness: 0.30, emissive: '#00e8ff', emissiveIntensity: 1.50, transparent: true, opacity: 0.35 },
  { id: 'ew-vfx-hologram-blue',   name: 'Hologramme Bleu',          category: 'vfx', color: '#2060ff', roughness: 0.10, metalness: 0.30, emissive: '#2060ff', emissiveIntensity: 1.50, transparent: true, opacity: 0.35 },
  { id: 'ew-vfx-hologram-green',  name: 'Hologramme Vert',          category: 'vfx', color: '#00ff80', roughness: 0.10, metalness: 0.30, emissive: '#00ff80', emissiveIntensity: 1.50, transparent: true, opacity: 0.35 },
  { id: 'ew-vfx-energy-shield',   name: 'Bouclier Énergie',         category: 'vfx', color: '#4080ff', roughness: 0.05, metalness: 0.40, emissive: '#2060ff', emissiveIntensity: 1.20, transparent: true, opacity: 0.25 },
  { id: 'ew-vfx-lava',            name: 'Lave Incandescente',       category: 'vfx', color: '#ff2000', roughness: 0.80, metalness: 0.00, emissive: '#ff4000', emissiveIntensity: 1.80 },
  { id: 'ew-vfx-lava-glow',       name: 'Magma Rougeoyant',         category: 'vfx', color: '#cc1800', roughness: 0.75, metalness: 0.00, emissive: '#ff3000', emissiveIntensity: 2.50 },
  { id: 'ew-vfx-fire',            name: 'Flamme Orange',            category: 'vfx', color: '#ff5000', roughness: 0.50, metalness: 0.00, emissive: '#ff4000', emissiveIntensity: 2.00, transparent: true, opacity: 0.80 },
  { id: 'ew-vfx-fire-blue',       name: 'Flamme Bleue',             category: 'vfx', color: '#0060ff', roughness: 0.50, metalness: 0.00, emissive: '#0080ff', emissiveIntensity: 2.00, transparent: true, opacity: 0.80 },
  { id: 'ew-vfx-electricity',     name: 'Électricité Arc',          category: 'vfx', color: '#80c8ff', roughness: 0.10, metalness: 0.30, emissive: '#80c8ff', emissiveIntensity: 3.00, transparent: true, opacity: 0.70 },
  { id: 'ew-vfx-portal',          name: 'Portail Dimensionnel',     category: 'vfx', color: '#4000a0', roughness: 0.10, metalness: 0.30, emissive: '#8000ff', emissiveIntensity: 2.50, transparent: true, opacity: 0.60 },
  { id: 'ew-vfx-portal-orange',   name: 'Portail Orange',           category: 'vfx', color: '#ff4000', roughness: 0.10, metalness: 0.30, emissive: '#ff6000', emissiveIntensity: 2.50, transparent: true, opacity: 0.60 },
  { id: 'ew-vfx-crystal-blue',    name: 'Cristal Bleu',             category: 'vfx', color: '#60a0ff', roughness: 0.05, metalness: 0.50, emissive: '#2060c0', emissiveIntensity: 0.40, transparent: true, opacity: 0.65 },
  { id: 'ew-vfx-crystal-purple',  name: 'Cristal Violet',           category: 'vfx', color: '#8040ff', roughness: 0.05, metalness: 0.50, emissive: '#6020c0', emissiveIntensity: 0.40, transparent: true, opacity: 0.65 },
  { id: 'ew-vfx-crystal-green',   name: 'Cristal Vert',             category: 'vfx', color: '#20ff80', roughness: 0.05, metalness: 0.50, emissive: '#10c060', emissiveIntensity: 0.40, transparent: true, opacity: 0.65 },
  { id: 'ew-vfx-crystal-red',     name: 'Cristal Rouge',            category: 'vfx', color: '#ff4040', roughness: 0.05, metalness: 0.50, emissive: '#c02020', emissiveIntensity: 0.40, transparent: true, opacity: 0.65 },
  { id: 'ew-vfx-water-clear',     name: 'Eau Claire',               category: 'vfx', color: '#80c0ff', roughness: 0.03, metalness: 0.20, transparent: true, opacity: 0.40 },
  { id: 'ew-vfx-water-deep',      name: 'Eau Profonde',             category: 'vfx', color: '#102040', roughness: 0.05, metalness: 0.20, transparent: true, opacity: 0.65 },
  { id: 'ew-vfx-water-murky',     name: 'Eau Trouble',              category: 'vfx', color: '#404820', roughness: 0.10, metalness: 0.10, transparent: true, opacity: 0.72 },
  { id: 'ew-vfx-ice',             name: 'Glace',                    category: 'vfx', color: '#c0e0f0', roughness: 0.05, metalness: 0.10, emissive: '#80b8e0', emissiveIntensity: 0.10, transparent: true, opacity: 0.60 },
  { id: 'ew-vfx-ice-blue',        name: 'Glace Bleue',              category: 'vfx', color: '#80b8f0', roughness: 0.04, metalness: 0.15, emissive: '#4080c0', emissiveIntensity: 0.15, transparent: true, opacity: 0.55 },
  { id: 'ew-vfx-smoke',           name: 'Fumée',                    category: 'vfx', color: '#404850', roughness: 0.90, metalness: 0.00, transparent: true, opacity: 0.35 },
  { id: 'ew-vfx-smoke-white',     name: 'Fumée Blanche',            category: 'vfx', color: '#d0d4d8', roughness: 0.90, metalness: 0.00, transparent: true, opacity: 0.30 },
  { id: 'ew-vfx-force-field',     name: 'Champ de Force',           category: 'vfx', color: '#4080ff', roughness: 0.03, metalness: 0.50, emissive: '#2060d0', emissiveIntensity: 0.80, transparent: true, opacity: 0.18 },
  { id: 'ew-vfx-warp',            name: 'Distortion Spatiale',      category: 'vfx', color: '#8040ff', roughness: 0.02, metalness: 0.60, emissive: '#6020c0', emissiveIntensity: 1.00, transparent: true, opacity: 0.22 },
  { id: 'ew-vfx-scan-line',       name: 'Scan Numérique',           category: 'vfx', color: '#00e8ff', roughness: 0.10, metalness: 0.40, emissive: '#00e8ff', emissiveIntensity: 0.80, transparent: true, opacity: 0.45 },
  { id: 'ew-vfx-xray',            name: 'Rayons X',                 category: 'vfx', color: '#80e0ff', roughness: 0.05, metalness: 0.30, emissive: '#40b0e0', emissiveIntensity: 0.60, transparent: true, opacity: 0.30 },
  { id: 'ew-vfx-tron-blue',       name: 'TRON Bleu',                category: 'vfx', color: '#002040', roughness: 0.20, metalness: 0.40, emissive: '#00a0ff', emissiveIntensity: 1.00 },
  { id: 'ew-vfx-tron-orange',     name: 'TRON Orange',              category: 'vfx', color: '#200800', roughness: 0.20, metalness: 0.40, emissive: '#ff6000', emissiveIntensity: 1.00 },
  { id: 'ew-vfx-cyberpunk',       name: 'Cyberpunk Magenta',        category: 'vfx', color: '#200020', roughness: 0.25, metalness: 0.35, emissive: '#ff0080', emissiveIntensity: 0.90 },
  { id: 'ew-vfx-matrix',          name: 'Matrix Vert',              category: 'vfx', color: '#001800', roughness: 0.25, metalness: 0.30, emissive: '#00ff40', emissiveIntensity: 0.80, transparent: true, opacity: 0.85 },
  { id: 'ew-vfx-golden-hour',     name: 'Heure Dorée Soleil',       category: 'vfx', color: '#ff9030', roughness: 0.30, metalness: 0.20, emissive: '#ffa030', emissiveIntensity: 0.60 },
  { id: 'ew-vfx-sunset',          name: 'Coucher de Soleil',        category: 'vfx', color: '#ff4820', roughness: 0.35, metalness: 0.10, emissive: '#ff5030', emissiveIntensity: 0.80 },
  { id: 'ew-vfx-aurora',          name: 'Aurore Boréale',           category: 'vfx', color: '#00ff80', roughness: 0.15, metalness: 0.15, emissive: '#00d060', emissiveIntensity: 1.20, transparent: true, opacity: 0.55 },
  { id: 'ew-vfx-aurora-purple',   name: 'Aurore Violette',          category: 'vfx', color: '#6000ff', roughness: 0.15, metalness: 0.15, emissive: '#8000ff', emissiveIntensity: 1.20, transparent: true, opacity: 0.55 },
  { id: 'ew-vfx-ghost',           name: 'Fantôme',                  category: 'vfx', color: '#c0d0e8', roughness: 0.20, metalness: 0.10, emissive: '#8090b0', emissiveIntensity: 0.40, transparent: true, opacity: 0.28 },
  { id: 'ew-vfx-invisible',       name: 'Invisibilité',             category: 'vfx', color: '#80b0d0', roughness: 0.02, metalness: 0.50, transparent: true, opacity: 0.08 },
  { id: 'ew-vfx-dark-matter',     name: 'Matière Noire',            category: 'vfx', color: '#050508', roughness: 0.80, metalness: 0.00, emissive: '#100030', emissiveIntensity: 0.30 },
  { id: 'ew-vfx-star',            name: 'Étoile Lumineuse',         category: 'vfx', color: '#ffffff', roughness: 0.10, metalness: 0.20, emissive: '#ffe8a0', emissiveIntensity: 3.00 },
  { id: 'ew-vfx-supernova',       name: 'Supernova',                category: 'vfx', color: '#ffffff', roughness: 0.10, metalness: 0.20, emissive: '#ff8000', emissiveIntensity: 5.00 },
  { id: 'ew-vfx-black-hole',      name: 'Trou Noir',                category: 'vfx', color: '#000000', roughness: 0.00, metalness: 1.00, emissive: '#200040', emissiveIntensity: 0.20 },
  { id: 'ew-vfx-rainbow',         name: 'Spectre Arc-en-ciel',      category: 'vfx', color: '#ff4060', roughness: 0.15, metalness: 0.15, emissive: '#ff0040', emissiveIntensity: 0.50, transparent: true, opacity: 0.75 },
  { id: 'ew-vfx-screen-troxt',    name: 'Écran TroxT',              category: 'vfx', color: '#02101b', roughness: 0.18, metalness: 0.15, emissive: '#00e8ff', emissiveIntensity: 0.32 },
  { id: 'ew-vfx-hud-green',       name: 'HUD Militaire Vert',       category: 'vfx', color: '#001800', roughness: 0.20, metalness: 0.30, emissive: '#00a030', emissiveIntensity: 0.60 },
  { id: 'ew-vfx-hud-blue',        name: 'HUD Bleu Interface',       category: 'vfx', color: '#000820', roughness: 0.20, metalness: 0.30, emissive: '#0060c0', emissiveIntensity: 0.60 },
  { id: 'ew-vfx-laser-red',       name: 'Laser Rouge',              category: 'vfx', color: '#ff0010', roughness: 0.05, metalness: 0.20, emissive: '#ff0000', emissiveIntensity: 4.00, transparent: true, opacity: 0.85 },
  { id: 'ew-vfx-laser-green',     name: 'Laser Vert',               category: 'vfx', color: '#00ff20', roughness: 0.05, metalness: 0.20, emissive: '#00ff00', emissiveIntensity: 4.00, transparent: true, opacity: 0.85 },
  { id: 'ew-vfx-laser-blue',      name: 'Laser Bleu',               category: 'vfx', color: '#0020ff', roughness: 0.05, metalness: 0.20, emissive: '#0040ff', emissiveIntensity: 4.00, transparent: true, opacity: 0.85 },
  { id: 'ew-vfx-explosion',       name: 'Explosion Flash',          category: 'vfx', color: '#ff8000', roughness: 0.40, metalness: 0.00, emissive: '#ff6000', emissiveIntensity: 3.00, transparent: true, opacity: 0.90 },

  // ============================================================
  // 🌿 TERRAIN / NATURE — 60 matériaux
  // ============================================================
  { id: 'ew-terrain-grass-green',  name: 'Gazon Vert Vif',          category: 'terrain', color: '#2a5c2a', roughness: 0.98, metalness: 0.00 },
  { id: 'ew-terrain-grass-dry',    name: 'Herbe Sèche',             category: 'terrain', color: '#a09040', roughness: 0.97, metalness: 0.00 },
  { id: 'ew-terrain-grass-dark',   name: 'Gazon Sombre',            category: 'terrain', color: '#1a3c1a', roughness: 0.98, metalness: 0.00 },
  { id: 'ew-terrain-soil',         name: 'Terre Brune',             category: 'terrain', color: '#5a3820', roughness: 0.96, metalness: 0.00 },
  { id: 'ew-terrain-soil-dark',    name: 'Terre Noire Fertile',     category: 'terrain', color: '#2a1c10', roughness: 0.97, metalness: 0.00 },
  { id: 'ew-terrain-sand',         name: 'Sable Chaud',             category: 'terrain', color: '#d4b880', roughness: 0.95, metalness: 0.00 },
  { id: 'ew-terrain-sand-wet',     name: 'Sable Mouillé',           category: 'terrain', color: '#b89a60', roughness: 0.90, metalness: 0.00 },
  { id: 'ew-terrain-gravel',       name: 'Gravier Gris',            category: 'terrain', color: '#8a8c90', roughness: 0.96, metalness: 0.00 },
  { id: 'ew-terrain-gravel-brown', name: 'Gravier Brun',            category: 'terrain', color: '#7a6040', roughness: 0.95, metalness: 0.00 },
  { id: 'ew-terrain-mud',          name: 'Boue',                    category: 'terrain', color: '#4a3a28', roughness: 0.97, metalness: 0.00 },
  { id: 'ew-terrain-snow-fresh',   name: 'Neige Fraîche',           category: 'terrain', color: '#f8fdff', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-terrain-snow-packed',  name: 'Neige Compactée',         category: 'terrain', color: '#d8e8f0', roughness: 0.70, metalness: 0.00 },
  { id: 'ew-terrain-ice-floor',    name: 'Glace Sol',               category: 'terrain', color: '#b0d8f0', roughness: 0.05, metalness: 0.08, transparent: true, opacity: 0.80 },
  { id: 'ew-terrain-asphalt',      name: 'Asphalte Route',          category: 'terrain', color: '#282c32', roughness: 0.97, metalness: 0.00 },
  { id: 'ew-terrain-asphalt-wet',  name: 'Asphalte Mouillé',        category: 'terrain', color: '#1a1e24', roughness: 0.60, metalness: 0.05 },
  { id: 'ew-terrain-concrete-rd',  name: 'Béton Route',             category: 'terrain', color: '#b8b4ae', roughness: 0.94, metalness: 0.00 },
  { id: 'ew-terrain-paving-stone', name: 'Pavé Pierre',             category: 'terrain', color: '#8a8c90', roughness: 0.90, metalness: 0.00 },
  { id: 'ew-terrain-paving-red',   name: 'Pavé Rouge',              category: 'terrain', color: '#7a3828', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-terrain-cobblestone',  name: 'Pavé Rond',               category: 'terrain', color: '#6a6860', roughness: 0.92, metalness: 0.00 },
  { id: 'ew-terrain-wood-deck',    name: 'Terrasse Bois Ext.',      category: 'terrain', color: '#8a6040', roughness: 0.78, metalness: 0.00 },
  { id: 'ew-terrain-rock-grey',    name: 'Roche Grise',             category: 'terrain', color: '#7a7c80', roughness: 0.96, metalness: 0.00 },
  { id: 'ew-terrain-rock-brown',   name: 'Roche Brune',             category: 'terrain', color: '#6a5040', roughness: 0.95, metalness: 0.00 },
  { id: 'ew-terrain-cliff',        name: 'Falaise Pierre',          category: 'terrain', color: '#8a8480', roughness: 0.97, metalness: 0.00 },
  { id: 'ew-terrain-moss',         name: 'Mousse',                  category: 'terrain', color: '#3a5830', roughness: 0.98, metalness: 0.00 },
  { id: 'ew-terrain-leaves',       name: 'Feuilles Sol',            category: 'terrain', color: '#6a5028', roughness: 0.96, metalness: 0.00 },
  { id: 'ew-terrain-bark',         name: 'Écorce Pin',              category: 'terrain', color: '#5a4030', roughness: 0.93, metalness: 0.00 },
  { id: 'ew-terrain-grass-qc',     name: 'Gazon Québec',            category: 'terrain', color: '#294c2b', roughness: 1.00, metalness: 0.00 },
  { id: 'ew-terrain-asphalt-night',name: 'Asphalte Nuit',           category: 'terrain', color: '#1b1f25', roughness: 0.98, metalness: 0.00 },
  { id: 'ew-terrain-grass-frost',  name: 'Gazon Gelé',              category: 'terrain', color: '#8aaa90', roughness: 0.95, metalness: 0.00 },
  { id: 'ew-terrain-water-surface',name: 'Surface Eau',             category: 'terrain', color: '#2060a0', roughness: 0.05, metalness: 0.20, transparent: true, opacity: 0.70 },
  { id: 'ew-terrain-swamp',        name: 'Marécage',                category: 'terrain', color: '#283820', roughness: 0.88, metalness: 0.00, transparent: true, opacity: 0.85 },
  { id: 'ew-terrain-pine-needle',  name: 'Aiguilles de Pin Sol',    category: 'terrain', color: '#4a3820', roughness: 0.95, metalness: 0.00 },
  { id: 'ew-terrain-flower-field', name: 'Prairie Fleurie',         category: 'terrain', color: '#6a9040', roughness: 0.97, metalness: 0.00 },
  { id: 'ew-terrain-agricultural', name: 'Champ Agricole',          category: 'terrain', color: '#7a6030', roughness: 0.96, metalness: 0.00 },
  { id: 'ew-terrain-gravel-road',  name: 'Chemin de Gravier',       category: 'terrain', color: '#9a9490', roughness: 0.95, metalness: 0.00 },
  { id: 'ew-terrain-desert',       name: 'Désert Sable',            category: 'terrain', color: '#c8a060', roughness: 0.94, metalness: 0.00 },
  { id: 'ew-terrain-volcanic',     name: 'Sol Volcanique',          category: 'terrain', color: '#2a2420', roughness: 0.97, metalness: 0.02, emissive: '#400800', emissiveIntensity: 0.15 },
  { id: 'ew-terrain-moon',         name: 'Sol Lunaire',             category: 'terrain', color: '#9a9898', roughness: 0.96, metalness: 0.00 },
  { id: 'ew-terrain-mars',         name: 'Sol Martien Rouge',       category: 'terrain', color: '#8a4028', roughness: 0.97, metalness: 0.00 },
  { id: 'ew-terrain-alien-purple', name: 'Sol Alien Violet',        category: 'terrain', color: '#382048', roughness: 0.90, metalness: 0.05, emissive: '#200040', emissiveIntensity: 0.10 },
  { id: 'ew-terrain-underwater',   name: 'Fond Marin Sable',        category: 'terrain', color: '#9aac80', roughness: 0.92, metalness: 0.00 },
  { id: 'ew-terrain-reef',         name: 'Récif Corallien',         category: 'terrain', color: '#d07848', roughness: 0.90, metalness: 0.00 },

  // ── Nature — arbres ──────────────────────────────────────
  { id: 'ew-nature-trunk',         name: 'Tronc Naturel',           category: 'nature', color: '#6b442c', roughness: 0.90, metalness: 0.00 },
  { id: 'ew-nature-pine',          name: 'Pin Sombre',              category: 'nature', color: '#173d25', roughness: 0.95, metalness: 0.00 },
  { id: 'ew-nature-leaf-green',    name: 'Feuillage Vivant',        category: 'nature', color: '#2f7a3d', roughness: 0.95, metalness: 0.00 },
  { id: 'ew-nature-leaf-autumn',   name: 'Feuillage Automne',       category: 'nature', color: '#c06020', roughness: 0.95, metalness: 0.00 },
  { id: 'ew-nature-leaf-dead',     name: 'Feuille Morte',           category: 'nature', color: '#8a6030', roughness: 0.97, metalness: 0.00 },
  { id: 'ew-nature-birch-bark',    name: 'Écorce Bouleau',          category: 'nature', color: '#e0d8c8', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-nature-willow',        name: 'Saule Pleureur',          category: 'nature', color: '#5a8040', roughness: 0.94, metalness: 0.00 },
  { id: 'ew-nature-bamboo',        name: 'Bambou Vert',             category: 'nature', color: '#6a8c38', roughness: 0.78, metalness: 0.00 },
  { id: 'ew-nature-flower-red',    name: 'Fleur Rouge',             category: 'nature', color: '#c02030', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-nature-flower-white',  name: 'Fleur Blanche',           category: 'nature', color: '#f4f0ea', roughness: 0.88, metalness: 0.00 },
  { id: 'ew-nature-mushroom',      name: 'Champignon',              category: 'nature', color: '#c09848', roughness: 0.90, metalness: 0.00 },
  { id: 'ew-nature-cactus',        name: 'Cactus',                  category: 'nature', color: '#4a7828', roughness: 0.85, metalness: 0.00 },
  { id: 'ew-nature-seaweed',       name: 'Algues Marines',          category: 'nature', color: '#1a5c30', roughness: 0.90, metalness: 0.00 },

  // ============================================================
  // 🪟 VERRE & TRANSPARENTS — 30 matériaux
  // ============================================================
  { id: 'ew-glass-clear',          name: 'Verre Transparent',       category: 'glass', color: '#c8dce8', roughness: 0.03, metalness: 0.10, transparent: true, opacity: 0.15 },
  { id: 'ew-glass-tinted-grey',    name: 'Verre Teinté Gris',       category: 'glass', color: '#606870', roughness: 0.05, metalness: 0.12, transparent: true, opacity: 0.45 },
  { id: 'ew-glass-tinted-blue',    name: 'Verre Teinté Bleu',       category: 'glass', color: '#204060', roughness: 0.05, metalness: 0.12, transparent: true, opacity: 0.50 },
  { id: 'ew-glass-tinted-green',   name: 'Verre Teinté Vert',       category: 'glass', color: '#204030', roughness: 0.05, metalness: 0.12, transparent: true, opacity: 0.50 },
  { id: 'ew-glass-mirror',         name: 'Verre Miroir',            category: 'glass', color: '#b0c8d8', roughness: 0.02, metalness: 0.95, transparent: true, opacity: 0.90 },
  { id: 'ew-glass-cyan',           name: 'Verre Cyan',              category: 'glass', color: '#9beaff', roughness: 0.05, metalness: 0.10, transparent: true, opacity: 0.34 },
  { id: 'ew-glass-door-premium',   name: 'Verre Porte Premium',     category: 'glass', color: '#9beaff', roughness: 0.04, metalness: 0.12, transparent: true, opacity: 0.46 },
  { id: 'ew-glass-frosted',        name: 'Verre Dépoli',            category: 'glass', color: '#d8e4ec', roughness: 0.60, metalness: 0.05, transparent: true, opacity: 0.70 },
  { id: 'ew-glass-bulletproof',    name: 'Verre Blindé',            category: 'glass', color: '#c8d8e0', roughness: 0.10, metalness: 0.05, transparent: true, opacity: 0.50 },
  { id: 'ew-glass-solar',          name: 'Verre Solaire',           category: 'glass', color: '#1a3040', roughness: 0.12, metalness: 0.20, transparent: true, opacity: 0.60 },
  { id: 'ew-glass-amber',          name: 'Verre Ambré',             category: 'glass', color: '#c08020', roughness: 0.08, metalness: 0.08, transparent: true, opacity: 0.55 },
  { id: 'ew-glass-wine-red',       name: 'Verre Rouge Vin',         category: 'glass', color: '#600020', roughness: 0.06, metalness: 0.08, transparent: true, opacity: 0.50 },
  { id: 'ew-glass-neon-lit',       name: 'Verre Néon Éclairé',      category: 'glass', color: '#00e8ff', roughness: 0.08, metalness: 0.15, emissive: '#00e8ff', emissiveIntensity: 0.60, transparent: true, opacity: 0.55 },
  { id: 'ew-glass-crystal-ball',   name: 'Boule de Cristal',        category: 'glass', color: '#d0e0f0', roughness: 0.02, metalness: 0.30, transparent: true, opacity: 0.30 },
  { id: 'ew-glass-fiber-optic',    name: 'Fibre Optique',           category: 'glass', color: '#c8e0ff', roughness: 0.05, metalness: 0.20, emissive: '#80c0ff', emissiveIntensity: 0.80, transparent: true, opacity: 0.70 },
  { id: 'ew-acrylic-clear',        name: 'Acrylique Transparent',   category: 'glass', color: '#d4e4f0', roughness: 0.12, metalness: 0.05, transparent: true, opacity: 0.35 },
  { id: 'ew-acrylic-white',        name: 'Acrylique Blanc',         category: 'glass', color: '#f0eee8', roughness: 0.20, metalness: 0.03, transparent: true, opacity: 0.80 },
  { id: 'ew-polycarbonate',        name: 'Polycarbonate Dépoli',    category: 'glass', color: '#e0e8f0', roughness: 0.45, metalness: 0.05, transparent: true, opacity: 0.75 },

  // ============================================================
  // 💡 LUMIÈRES — 30 matériaux
  // ============================================================
  { id: 'ew-light-warm-led',       name: 'LED Blanc Chaud 3000K',   category: 'light', color: '#ffd39a', roughness: 0.20, metalness: 0.10, emissive: '#ffd39a', emissiveIntensity: 1.25 },
  { id: 'ew-light-cool-led',       name: 'LED Blanc Froid 6500K',   category: 'light', color: '#e8f0ff', roughness: 0.20, metalness: 0.10, emissive: '#e8f0ff', emissiveIntensity: 1.30 },
  { id: 'ew-light-neon-accent',    name: 'Néon Ether Cyan',         category: 'light', color: '#00e8ff', roughness: 0.20, metalness: 0.15, emissive: '#00e8ff', emissiveIntensity: 1.30 },
  { id: 'ew-light-screen-troxt',   name: 'Écran TroxT Glow',        category: 'light', color: '#02101b', roughness: 0.18, metalness: 0.15, emissive: '#00e8ff', emissiveIntensity: 0.32 },
  { id: 'ew-light-sodium',         name: 'Lampe Sodium Orange',     category: 'light', color: '#ff8020', roughness: 0.25, metalness: 0.10, emissive: '#ff7010', emissiveIntensity: 1.50 },
  { id: 'ew-light-fluorescent',    name: 'Néon Fluorescent',        category: 'light', color: '#e0f0ff', roughness: 0.20, metalness: 0.10, emissive: '#c0e0ff', emissiveIntensity: 1.20 },
  { id: 'ew-light-candle',         name: 'Bougie Flamme',           category: 'light', color: '#ff8030', roughness: 0.40, metalness: 0.00, emissive: '#ff6020', emissiveIntensity: 0.90, transparent: true, opacity: 0.85 },
  { id: 'ew-light-fireplace-glow', name: 'Foyer Lueur',             category: 'light', color: '#ff4010', roughness: 0.50, metalness: 0.00, emissive: '#ff3800', emissiveIntensity: 1.80 },
  { id: 'ew-light-emergency-red',  name: 'Lumière Urgence Rouge',   category: 'light', color: '#ff0010', roughness: 0.20, metalness: 0.20, emissive: '#ff0000', emissiveIntensity: 2.00 },
  { id: 'ew-light-emergency-blue', name: 'Lumière Police Bleue',    category: 'light', color: '#0020ff', roughness: 0.20, metalness: 0.20, emissive: '#0030ff', emissiveIntensity: 2.00 },
  { id: 'ew-light-strobe',         name: 'Stroboscope Blanc',       category: 'light', color: '#ffffff', roughness: 0.15, metalness: 0.15, emissive: '#ffffff', emissiveIntensity: 3.00 },
  { id: 'ew-light-blacklight',     name: 'Lumière Noire UV',        category: 'light', color: '#3a00c0', roughness: 0.20, metalness: 0.15, emissive: '#6000ff', emissiveIntensity: 1.00 },
  { id: 'ew-light-laser-pointer',  name: 'Pointeur Laser',          category: 'light', color: '#ff0010', roughness: 0.05, metalness: 0.20, emissive: '#ff0000', emissiveIntensity: 5.00, transparent: true, opacity: 0.80 },
  { id: 'ew-light-moon',           name: 'Clair de Lune',           category: 'light', color: '#8898b8', roughness: 0.20, metalness: 0.10, emissive: '#6080a0', emissiveIntensity: 0.50 },
  { id: 'ew-light-dawn',           name: 'Aube Bleutée',            category: 'light', color: '#8090c0', roughness: 0.25, metalness: 0.10, emissive: '#6070b0', emissiveIntensity: 0.60 },
  { id: 'ew-light-sunset-orange',  name: 'Coucher Soleil Orange',   category: 'light', color: '#ff5820', roughness: 0.30, metalness: 0.10, emissive: '#ff4010', emissiveIntensity: 1.00 },
  { id: 'ew-light-bioluminescent', name: 'Bioluminescence',         category: 'light', color: '#00a080', roughness: 0.30, metalness: 0.10, emissive: '#00c0a0', emissiveIntensity: 0.80, transparent: true, opacity: 0.70 },
  { id: 'ew-light-radioactive',    name: 'Radioactif Vert',         category: 'light', color: '#406020', roughness: 0.30, metalness: 0.15, emissive: '#80ff00', emissiveIntensity: 1.20, transparent: true, opacity: 0.80 },

  // ============================================================
  // 🛠️ ADDONS SPÉCIAUX — 30 matériaux
  // ============================================================
  { id: 'ew-addon-gold-leaf',      name: 'Feuille d\'Or',           category: 'addon', color: '#c9a840', roughness: 0.12, metalness: 0.98 },
  { id: 'ew-addon-silver-leaf',    name: 'Feuille d\'Argent',       category: 'addon', color: '#c0c8d0', roughness: 0.12, metalness: 0.97 },
  { id: 'ew-addon-diamond',        name: 'Diamant',                 category: 'addon', color: '#e8f4ff', roughness: 0.02, metalness: 0.10, transparent: true, opacity: 0.25 },
  { id: 'ew-addon-ruby',           name: 'Rubis',                   category: 'addon', color: '#c01828', roughness: 0.04, metalness: 0.10, emissive: '#800010', emissiveIntensity: 0.30, transparent: true, opacity: 0.60 },
  { id: 'ew-addon-emerald',        name: 'Émeraude',                category: 'addon', color: '#1a8040', roughness: 0.04, metalness: 0.10, emissive: '#006020', emissiveIntensity: 0.30, transparent: true, opacity: 0.60 },
  { id: 'ew-addon-sapphire',       name: 'Saphir',                  category: 'addon', color: '#1a40a0', roughness: 0.04, metalness: 0.10, emissive: '#1030a0', emissiveIntensity: 0.30, transparent: true, opacity: 0.60 },
  { id: 'ew-addon-pearl',          name: 'Nacre Perle',             category: 'addon', color: '#f0eee8', roughness: 0.15, metalness: 0.30 },
  { id: 'ew-addon-obsidian',       name: 'Obsidienne',              category: 'addon', color: '#0a0a0e', roughness: 0.08, metalness: 0.25 },
  { id: 'ew-addon-matte-black',    name: 'Noir Absolu Mat',         category: 'addon', color: '#050508', roughness: 0.98, metalness: 0.00 },
  { id: 'ew-addon-chrome-mirror',  name: 'Chrome Miroir',           category: 'addon', color: '#e0e4e8', roughness: 0.02, metalness: 0.99 },
  { id: 'ew-addon-iridescent',     name: 'Irisé Holographique',     category: 'addon', color: '#80c0ff', roughness: 0.10, metalness: 0.60, emissive: '#4080c0', emissiveIntensity: 0.20 },
  { id: 'ew-addon-metallic-red',   name: 'Métallique Rouge',        category: 'addon', color: '#c01818', roughness: 0.12, metalness: 0.70 },
  { id: 'ew-addon-metallic-blue',  name: 'Métallique Bleu',         category: 'addon', color: '#1840c0', roughness: 0.12, metalness: 0.70 },
  { id: 'ew-addon-metallic-green', name: 'Métallique Vert',         category: 'addon', color: '#186030', roughness: 0.12, metalness: 0.70 },
  { id: 'ew-addon-metallic-gold',  name: 'Métallique Or',           category: 'addon', color: '#c09030', roughness: 0.10, metalness: 0.80 },
  { id: 'ew-addon-velvet-dark',    name: 'Velours Noir Profond',    category: 'addon', color: '#0a0c10', roughness: 0.97, metalness: 0.00 },
  { id: 'ew-addon-suede-grey',     name: 'Daim Gris',               category: 'addon', color: '#8a8888', roughness: 0.92, metalness: 0.00 },
  { id: 'ew-addon-patent-black',   name: 'Verni Noir',              category: 'addon', color: '#0a0c0e', roughness: 0.04, metalness: 0.25 },
  { id: 'ew-addon-patent-red',     name: 'Verni Rouge',             category: 'addon', color: '#980c0c', roughness: 0.04, metalness: 0.22 },
  { id: 'ew-addon-washi-white',    name: 'Papier Washi Blanc',      category: 'addon', color: '#f4f0e8', roughness: 0.90, metalness: 0.00, transparent: true, opacity: 0.85 },
  { id: 'ew-addon-concrete-smooth',name: 'Béton Ultra Lisse',       category: 'addon', color: '#c8c4be', roughness: 0.15, metalness: 0.05 },
  { id: 'ew-addon-terrazzo-white', name: 'Terrazzo Blanc',          category: 'addon', color: '#e8e4dc', roughness: 0.25, metalness: 0.03 },
  { id: 'ew-addon-lace',           name: 'Dentelle Blanche',        category: 'addon', color: '#f8f6f2', roughness: 0.90, metalness: 0.00, transparent: true, opacity: 0.65 },
  { id: 'ew-addon-mesh-black',     name: 'Filet Noir',              category: 'addon', color: '#1a1c20', roughness: 0.80, metalness: 0.10, transparent: true, opacity: 0.60 },
  { id: 'ew-addon-paint-drip',     name: 'Peinture Graffiti Bleu',  category: 'addon', color: '#1840a0', roughness: 0.70, metalness: 0.00 },
  { id: 'ew-addon-paint-drip-red', name: 'Peinture Graffiti Rouge', category: 'addon', color: '#a01018', roughness: 0.70, metalness: 0.00 },
  { id: 'ew-addon-patina-bronze',  name: 'Patine Bronze',           category: 'addon', color: '#4a8060', roughness: 0.72, metalness: 0.55 },
  { id: 'ew-addon-aged-wood',      name: 'Bois Récupéré',           category: 'addon', color: '#7a6848', roughness: 0.93, metalness: 0.00 },
  { id: 'ew-addon-burned-wood',    name: 'Bois Brûlé Shou Sugi',    category: 'addon', color: '#141210', roughness: 0.88, metalness: 0.02 },
  { id: 'ew-addon-resin-clear',    name: 'Résine Époxy Claire',     category: 'addon', color: '#d0e8f4', roughness: 0.05, metalness: 0.05, transparent: true, opacity: 0.50 },
]

// ─────────────────────────────────────────────
// INDEX O(1) LOOKUP
// ─────────────────────────────────────────────
export const MATERIALS_INDEX = new Map<string, EtherMaterialDef>(
  ETHER_MATERIALS.map(m => [m.id, m])
)

// ─────────────────────────────────────────────
// CATÉGORIES
// ─────────────────────────────────────────────
export const CATEGORIES = [
  ...new Set(ETHER_MATERIALS.map(m => m.category))
] as const

// ─────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────
export function getMaterialDef(id?: string): EtherMaterialDef {
  return MATERIALS_INDEX.get(id ?? '') ?? ETHER_MATERIALS[0]
}

export function getMaterialsByCategory(category: string): EtherMaterialDef[] {
  return ETHER_MATERIALS.filter(m => m.category === category)
}

export function searchMaterials(query: string): EtherMaterialDef[] {
  const q = query.toLowerCase()
  return ETHER_MATERIALS.filter(m =>
    m.name.toLowerCase().includes(q) ||
    m.id.toLowerCase().includes(q) ||
    m.category.toLowerCase().includes(q)
  )
}

export function getEmissiveMaterials(): EtherMaterialDef[] {
  return ETHER_MATERIALS.filter(m => m.emissive && (m.emissiveIntensity ?? 0) > 0)
}

export function getTransparentMaterials(): EtherMaterialDef[] {
  return ETHER_MATERIALS.filter(m => m.transparent || (m.opacity ?? 1) < 1)
}

// ─────────────────────────────────────────────
// STATS
// ─────────────────────────────────────────────
export const CATALOG_STATS = {
  total:       ETHER_MATERIALS.length,
  categories:  CATEGORIES.length,
  emissive:    ETHER_MATERIALS.filter(m => m.emissive).length,
  transparent: ETHER_MATERIALS.filter(m => m.transparent).length,
  byCategory:  Object.fromEntries(
    [...new Set(ETHER_MATERIALS.map(m => m.category))].map(cat => [
      cat,
      ETHER_MATERIALS.filter(m => m.category === cat).length
    ])
  ),
} as const

console.log(`🌍 EtherMaterials chargé: ${CATALOG_STATS.total} matériaux · ${CATALOG_STATS.categories} catégories`)

// ─────────────────────────────────────────────
// EXPORT PAR DÉFAUT
// ─────────────────────────────────────────────
export default ETHER_MATERIALS